-- PRISTEEL contact provenance
-- Migrim shtues: nuk ndryshon dhe nuk fshin asnje rekord ekzistues ne contacts.

begin;

create table if not exists public.contact_sources (
  id bigint generated by default as identity primary key,
  contact_id text not null,
  email text,
  source text not null,
  external_id text,
  external_url text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_sources_contact_source_key unique (contact_id, source)
);

create index if not exists contact_sources_email_idx
  on public.contact_sources (lower(email));
create index if not exists contact_sources_source_idx
  on public.contact_sources (source, last_seen desc);
create unique index if not exists contact_sources_external_key
  on public.contact_sources (source, external_id)
  where external_id is not null;

-- Backfill vetem burimin qe mund ta provojme pa hamendje: HubSpot.
-- Kontaktet pa hubspot_id lihen pa burim derisa nje sync i verifikuar t'i preke.
insert into public.contact_sources
  (contact_id, email, source, external_id, external_url, first_seen, last_seen, updated_at)
select
  c.id::text,
  c.email,
  'hubspot',
  c.hubspot_id::text,
  c.hubspot_url,
  now(),
  now(),
  now()
from public.contacts c
where c.hubspot_id is not null
on conflict (contact_id, source) do update set
  email = excluded.email,
  external_id = coalesce(excluded.external_id, public.contact_sources.external_id),
  external_url = coalesce(excluded.external_url, public.contact_sources.external_url),
  last_seen = excluded.last_seen,
  updated_at = now();

alter table public.contact_sources enable row level security;

drop policy if exists contact_sources_authenticated_all on public.contact_sources;
create policy contact_sources_authenticated_all
  on public.contact_sources for all to authenticated
  using (true) with check (true);

commit;
