-- PRISTEEL: Emailat e lidhur me projektet
-- Ekzekutoje të plotë në Supabase SQL Editor.
-- Tipi i projects.id zbulohet automatikisht para krijimit të foreign keys.

do $$
declare
  project_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into project_id_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relname = 'projects'
    and a.attname = 'id'
    and a.attnum > 0
    and not a.attisdropped;

  if project_id_type is null then
    raise exception 'Nuk u gjet public.projects.id';
  end if;

  execute format($sql$
    create table if not exists public.project_emails (
      id bigint generated by default as identity primary key,
      project_id %1$s references public.projects(id) on delete set null,
      suggested_project_id %1$s references public.projects(id) on delete set null,
      gmail_message_id text not null,
      gmail_thread_id text not null,
      rfc822_message_id text,
      from_email text,
      from_name text,
      to_emails text[] not null default '{}',
      cc_emails text[] not null default '{}',
      subject text not null default '(pa subjekt)',
      snippet text not null default '',
      sent_at timestamptz not null,
      direction text not null check (direction in ('incoming','outgoing')),
      has_attachments boolean not null default false,
      gmail_url text,
      match_method text,
      match_confidence integer not null default 0 check (match_confidence between 0 and 100),
      created_at timestamptz not null default now(),
      updated_at timestamptz not null default now(),
      constraint project_emails_gmail_message_id_key unique (gmail_message_id)
    )
  $sql$, project_id_type);
end $$;

create index if not exists project_emails_project_sent_idx
  on public.project_emails(project_id, sent_at desc);

create index if not exists project_emails_suggested_sent_idx
  on public.project_emails(suggested_project_id, sent_at desc)
  where project_id is null;

create index if not exists project_emails_thread_idx
  on public.project_emails(gmail_thread_id);

alter table public.project_emails enable row level security;

drop policy if exists "project_emails_select_authenticated" on public.project_emails;
create policy "project_emails_select_authenticated"
  on public.project_emails
  for select
  to authenticated
  using (auth.role() = 'authenticated');

drop policy if exists "project_emails_insert_can_write" on public.project_emails;
create policy "project_emails_insert_can_write"
  on public.project_emails
  for insert
  to authenticated
  with check (public.can_write());

drop policy if exists "project_emails_update_can_write" on public.project_emails;
create policy "project_emails_update_can_write"
  on public.project_emails
  for update
  to authenticated
  using (public.can_write())
  with check (public.can_write());

drop policy if exists "project_emails_delete_can_write" on public.project_emails;
create policy "project_emails_delete_can_write"
  on public.project_emails
  for delete
  to authenticated
  using (public.can_write());

grant select, insert, update, delete on public.project_emails to authenticated;
grant usage, select on sequence public.project_emails_id_seq to authenticated;
