import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')!;
const GMAIL_USER=(Deno.env.get('GMAIL_USER')||'').toLowerCase();
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const REGISTRY='pppp_opportunity_outreach_registry_v1';
const VERSION='pppp-opportunity-outreach-sent-sync-v1';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-pppp-cron-secret','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Content-Type':'application/json'};
const text=(v:any,max=4000)=>String(v==null?'':v).trim().slice(0,max);

function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;const sa=JSON.parse(SA_JSON),scope='https://www.googleapis.com/auth/gmail.readonly',header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),data=await r.json();if(!r.ok)throw new Error(`token ${r.status}: ${JSON.stringify(data).slice(0,500)}`);cachedToken={token:data.access_token,exp:now+(data.expires_in||3600)};return cachedToken.token;}
async function authorized(req:Request){const provided=req.headers.get('x-pppp-cron-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided});return !error&&data===true;}
function hdr(m:any,name:string){return text((m?.payload?.headers||[]).find((x:any)=>String(x?.name||'').toLowerCase()===name.toLowerCase())?.value,1200);}
async function gmailMessage(id:string){const tk=await token(),u=new URL(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/messages/${encodeURIComponent(id)}`);u.searchParams.set('format','metadata');for(const h of ['Message-ID','X-PPPP-Outreach-ID','X-PPPP-Action-ID','To','Date'])u.searchParams.append('metadataHeaders',h);const r=await fetch(u,{headers:{Authorization:`Bearer ${tk}`}}),raw=await r.text();if(!r.ok)throw new Error(`Gmail message ${r.status}: ${raw.slice(0,600)}`);return JSON.parse(raw);}
async function findSent(row:any){const tk=await token(),u=new URL(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/messages`);u.searchParams.set('q',`in:sent rfc822msgid:${row.rfc_message_id}`);u.searchParams.set('maxResults','5');const r=await fetch(u,{headers:{Authorization:`Bearer ${tk}`}}),raw=await r.text();if(!r.ok)throw new Error(`Gmail sent search ${r.status}: ${raw.slice(0,600)}`);const data=JSON.parse(raw||'{}');for(const item of data.messages||[]){const m=await gmailMessage(item.id),labels=new Set((m?.labelIds||[]).map(String));if(!labels.has('SENT'))continue;const x=hdr(m,'X-PPPP-Outreach-ID'),mid=hdr(m,'Message-ID'),aid=hdr(m,'X-PPPP-Action-ID');if(x===row.outreach_id||mid===row.rfc_message_id||(aid===row.action_id&&mid===row.rfc_message_id))return m;}return null;}
function sentAt(meta:any){const ms=Number(meta?.internalDate||0);return Number.isFinite(ms)&&ms>0?new Date(ms).toISOString():new Date().toISOString();}

async function refreshActionPayload(actionId:string){const a=await db.from('pppp_opportunity_actions').select('id,payload').eq('id',actionId).maybeSingle();if(a.error)throw a.error;if(!a.data)return;const r=await db.from(REGISTRY).select('*').eq('action_id',actionId).order('created_at',{ascending:true});if(r.error)throw r.error;const rows=r.data||[],drafts=rows.map((x:any)=>({email:x.recipient_email,name:x.recipient_name||null,draft_id:x.gmail_draft_id||null,message_id:x.gmail_message_id||x.gmail_draft_message_id||null,thread_id:x.gmail_thread_id||null,created_at:x.draft_created_at||x.created_at,updated_at:x.updated_at,generator:x.generator||null,language:x.language||null,subject:x.subject||null,mime_type:x.mime_type||null,html:x.html===true,status:x.status,outreach_id:x.outreach_id,rfc_message_id:x.rfc_message_id,sent_at:x.sent_at||null})),firstDraft=rows.find((x:any)=>x.status==='draft_created'),firstAny=rows[0]||null,p=a.data.payload&&typeof a.data.payload==='object'?a.data.payload:{},next={...p,gmail_drafts:drafts,gmail_draft_count:rows.filter((x:any)=>x.status==='draft_created').length,gmail_sent_count:rows.filter((x:any)=>x.status==='sent').length,gmail_outreach_registry_version:'v1',gmail_draft_write_policy:'registry_state_machine_v1',gmail_auto_send:false,human_send_required:true,gmail_draft_id:firstDraft?.gmail_draft_id||null,gmail_message_id:firstAny?.gmail_message_id||firstAny?.gmail_draft_message_id||null,gmail_thread_id:firstAny?.gmail_thread_id||null,gmail_draft_created_at:firstDraft?.draft_created_at||null};const u=await db.from('pppp_opportunity_actions').update({payload:next,updated_at:new Date().toISOString()}).eq('id',actionId);if(u.error)throw u.error;}

async function syncRow(row:any){const now=new Date().toISOString();try{const meta=await findSent(row);if(!meta){const u=await db.from(REGISTRY).update({last_checked_at:now,last_error:null,updated_at:now}).eq('id',row.id);if(u.error)throw u.error;return{outreach_id:row.outreach_id,status:'draft_created',changed:false};}const method=hdr(meta,'X-PPPP-Outreach-ID')===row.outreach_id?'x-pppp-outreach-id':'rfc822-message-id',patch={status:'sent',gmail_message_id:meta.id,gmail_thread_id:meta.threadId||null,sent_at:sentAt(meta),last_checked_at:now,last_error:null,updated_at:now,payload:{...(row.payload||{}),sent_match_method:method,sent_sync_version:VERSION}};const u=await db.from(REGISTRY).update(patch).eq('id',row.id);if(u.error)throw u.error;await refreshActionPayload(row.action_id);return{outreach_id:row.outreach_id,status:'sent',changed:true,gmail_message_id:meta.id,gmail_thread_id:meta.threadId||null,match_method:method};}catch(e){await db.from(REGISTRY).update({last_checked_at:now,last_error:text((e as any)?.message||e,1000),updated_at:now}).eq('id',row.id);return{outreach_id:row.outreach_id,status:row.status,changed:false,error:text((e as any)?.message||e,500)};}}
async function run(limit=250){const safe=Math.max(1,Math.min(500,Number(limit)||250)),q=await db.from(REGISTRY).select('*').eq('status','draft_created').order('draft_created_at',{ascending:true}).limit(safe);if(q.error)throw q.error;const items:any[]=[],changedActions=new Set<string>();for(const row of q.data||[]){const r=await syncRow(row);items.push(r);if(r.changed)changedActions.add(row.action_id);}return{checked:(q.data||[]).length,sent_marked:items.filter(x=>x.changed).length,pending:items.filter(x=>!x.changed&&!x.error).length,errors:items.filter(x=>x.error).length,actions_changed:changedActions.size,items:items.slice(0,300),version:VERSION,human_send_required:true,auto_send:false};}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!(await authorized(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:cors});try{const u=new URL(req.url),out=await run(Number(u.searchParams.get('limit')||250));return new Response(JSON.stringify({ok:true,...out}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:text((e as any)?.message||e,1000),auto_send:false,human_send_required:true}),{status:500,headers:cors});}});
