-- PRISTEEL Gmail / projektet
-- Migrim shtues: nuk fshin dhe nuk zevendeson lidhjet ekzistuese.

begin;

-- Nje email mund te lidhet me nje ose disa projekte.
create table if not exists public.project_email_links (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null,
  gmail_thread_id text,
  project_id text not null,
  link_method text not null default 'manual',
  confidence integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_email_links_message_project_key unique (gmail_message_id, project_id)
);

create index if not exists project_email_links_project_idx
  on public.project_email_links (project_id, created_at desc);
create index if not exists project_email_links_thread_idx
  on public.project_email_links (gmail_thread_id);
create index if not exists project_email_links_message_idx
  on public.project_email_links (gmail_message_id);

-- Shenjat per emaila/thread-e qe duhen kontrolluar manualisht.
alter table public.project_emails
  add column if not exists needs_review boolean not null default false;
alter table public.project_emails
  add column if not exists review_reason text;

-- Kontaktet qe i perkasin nje projekti. Emaili perdoret si identifikues i qendrueshem,
-- sepse tabela ekzistuese contacts mund te kete tipe te ndryshme ID-je ne instalime te ndryshme.
create table if not exists public.project_contacts (
  id bigint generated by default as identity primary key,
  project_id text not null,
  email text not null,
  name text,
  company text,
  role text,
  source text not null default 'email-auto',
  source_message_ids jsonb not null default '[]'::jsonb,
  first_seen timestamptz,
  last_seen timestamptz,
  email_count integer not null default 0,
  direct_count integer not null default 0,
  cc_count integer not null default 0,
  is_primary boolean not null default false,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_contacts_project_email_key unique (project_id, email)
);

create index if not exists project_contacts_project_idx
  on public.project_contacts (project_id, is_primary desc, last_seen desc);
create index if not exists project_contacts_email_idx
  on public.project_contacts (lower(email));

-- Pergatitje per ndarjen e attachment-eve nga i njejti email ne projekte te ndryshme.
create table if not exists public.project_attachment_links (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null,
  gmail_thread_id text,
  attachment_id text not null,
  attachment_name text,
  project_id text not null,
  drive_file_id text,
  link_method text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_attachment_links_unique unique (gmail_message_id, attachment_id, project_id)
);

create index if not exists project_attachment_links_project_idx
  on public.project_attachment_links (project_id, created_at desc);
create index if not exists project_attachment_links_message_idx
  on public.project_attachment_links (gmail_message_id);

-- Bart lidhjet aktuale ne tabelen e re. project_id ruhet edhe ne project_emails
-- per pajtueshmeri me funksionet e vjetra gjate migrimit.
insert into public.project_email_links
  (gmail_message_id, gmail_thread_id, project_id, link_method, confidence, created_at, updated_at)
select
  pe.gmail_message_id,
  pe.gmail_thread_id,
  pe.project_id::text,
  coalesce(pe.match_method, 'legacy-backfill'),
  coalesce(pe.match_confidence, 100),
  now(),
  coalesce(pe.updated_at, now())
from public.project_emails pe
where pe.project_id is not null
  and pe.gmail_message_id is not null
on conflict (gmail_message_id, project_id) do nothing;

-- Nese mesazhe te ndryshme te te njejtit thread jane lidhur me projekte te ndryshme,
-- thread-i shenohet per kontroll, por asnje lidhje nuk ndryshohet automatikisht.
with mixed_threads as (
  select gmail_thread_id
  from public.project_email_links
  where gmail_thread_id is not null
  group by gmail_thread_id
  having count(distinct project_id) > 1
)
update public.project_emails pe
set
  needs_review = true,
  review_reason = coalesce(pe.review_reason, 'Thread-i permban emaila te lidhur me disa projekte.'),
  updated_at = now()
where pe.gmail_thread_id in (select gmail_thread_id from mixed_threads);

-- RLS: platforma perdor sesion te autentikuar te Supabase.
alter table public.project_email_links enable row level security;
alter table public.project_contacts enable row level security;
alter table public.project_attachment_links enable row level security;

drop policy if exists project_email_links_authenticated_all on public.project_email_links;
create policy project_email_links_authenticated_all
  on public.project_email_links for all to authenticated
  using (true) with check (true);

drop policy if exists project_contacts_authenticated_all on public.project_contacts;
create policy project_contacts_authenticated_all
  on public.project_contacts for all to authenticated
  using (true) with check (true);

drop policy if exists project_attachment_links_authenticated_all on public.project_attachment_links;
create policy project_attachment_links_authenticated_all
  on public.project_attachment_links for all to authenticated
  using (true) with check (true);

commit;
