-- PRISTEEL Project Intelligence
-- Migrim shtues. Nuk fshin ose ndryshon të dhënat ekzistuese.

begin;

create table if not exists public.project_analyses (
  id bigint generated by default as identity primary key,
  project_id text not null,
  status text not null default 'complete',
  engine text not null default 'rules',
  model text,
  analysis jsonb not null default '{}'::jsonb,
  source_manifest jsonb not null default '[]'::jsonb,
  source_counts jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists project_analyses_project_created_idx
  on public.project_analyses (project_id, created_at desc);

create index if not exists project_analyses_status_idx
  on public.project_analyses (status);

alter table public.project_analyses enable row level security;

drop policy if exists project_analyses_authenticated_all
  on public.project_analyses;

create policy project_analyses_authenticated_all
  on public.project_analyses
  for all
  to authenticated
  using (true)
  with check (true);

commit;
