import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "jsr:@supabase/supabase-js@2";

const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'');
const JSON_HEADERS={'content-type':'application/json'};
const T=(v:any)=>String(v??'').trim();
const A=(v:any)=>Array.isArray(v)?v:[];
const U=(v:any[])=>[...new Set(A(v).map(T).filter(Boolean))];
const N=(v:any)=>T(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
const E=(v:any)=>(T(v).toLowerCase().match(/[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,}/)||[])[0]||'';
const W=(v:any)=>{const n=new Date(v||0).getTime();return Number.isFinite(n)?n:0};
const ISO=()=>new Date().toISOString();
const DAY=()=>ISO().slice(0,10);
const CL=(v:any,n=4000)=>T(v).replace(/\u0000/g,'').slice(0,n);
const CAPS=['fabrication','galvanizing','coating','heavy_plate','sheet','profiles','tubes','hardware','machining'];
const TERMINAL=['humbur','arkivuar','mbyllur','realizuar','lost','archived','cancelled','canceled'];
const CLOSED=['mbyllur','done','kryer'];
const PRI=['critical','high','medium','low'];
const CAT=['production_change','client_request','supplier_update','acknowledgement','technical_change','commercial_change','procurement_request','no_action','other'];
const INTENT=['procurement_prepare','await_supplier','supplier_response','await_client','commercial_offer','execution','review_required','no_action'];
const SCHEMA={type:'object',properties:{action_required:{type:'boolean'},priority:{type:'string',enum:PRI},category:{type:'string',enum:CAT},summary:{type:'string'},workflow_intent:{type:'string',enum:INTENT},confidence:{type:'integer',minimum:0,maximum:100},required_capabilities:{type:'array',items:{type:'string',enum:CAPS}},required_grades:{type:'array',items:{type:'string'}},requirements:{type:'array',items:{type:'string'}},risks:{type:'array',items:{type:'string'}},missing_information:{type:'array',items:{type:'string'}},recommended_supplier_names:{type:'array',items:{type:'string'}},rfq_scope_lines:{type:'array',items:{type:'string'}}},required:['action_required','priority','category','summary','workflow_intent','confidence','required_capabilities','required_grades','requirements','risks','missing_information','recommended_supplier_names','rfq_scope_lines'],additionalProperties:false};
const SYSTEM=`You are the local semantic intelligence layer inside PRISTEEL PPPP. /no_think Return only JSON matching the supplied schema. Deterministic PPPP rules are the safety authority and will override you. Never invent facts, prices, quantities, dates, standards, certificates, suppliers or commitments. Distinguish client/buyer emails, supplier emails and PRISTEEL outbound emails. recommended_supplier_names may contain ONLY exact names from supplier_candidates. Infer requirements and workflow intent only from supplied project, email, document and BOM context.`;

async function auth(req:Request){const x=req.headers.get('x-pppp-cron-secret')||'';if(!x)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided:x});return !error&&data===true}
async function hash(v:any){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(T(v)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function validGrade(v:any){const x=T(v).replace(/\s+/g,'');return /^(S(?:235|275|355|420|460)(?:JR|J0|J2|N|NL|M|ML|MC)?|(?:AH|DH|EH|FH)36)$/i.test(x)?x:''}
function gb(v:any){return N(v).replace(/(jr|j0|j2|n|nl|m|ml|mc)$/i,'')}
function bsum(rows:any[]){const kg=A(rows).reduce((s:number,x:any)=>s+Number(x.kg||0),0),latest=Math.max(0,...A(rows).map((x:any)=>W(x.created_at)));return{rows:A(rows).length,kg:Math.round(kg*100)/100,grades:U(A(rows).map((x:any)=>validGrade(x.grade||x.materiali)).filter(Boolean)),profiles:U(A(rows).map((x:any)=>x.profile)),surfaces:U(A(rows).map((x:any)=>x.surface).filter(Boolean)),standards:U(A(rows).map((x:any)=>x.std).filter(Boolean)),certs:U(A(rows).map((x:any)=>x.cert).filter(Boolean)),needs_review_rows:A(rows).filter((x:any)=>x.needs_review===true).length,latest_at:latest?new Date(latest).toISOString():null}}
function capabilities(p:any,b:any,docs:any[]){const j=N([p.name,p.notes,p.deal_type,b.profiles.join(' '),b.surfaces.join(' '),b.standards.join(' '),...A(docs).slice(0,8).map((x:any)=>JSON.stringify(x.extracted_data||{}))].join(' ')),out:string[]=[];if(b.rows||/fabric|prodh|konstruksion|construction|weld|stahl|celik/.test(j))out.push('fabrication');if(/galvan|zink|zinc|hot dip|feuerverzink/.test(j))out.push('galvanizing');if(/powder|plastifik|coat|paint|lackier/.test(j))out.push('coating');if(/plate|pllak|blech|heavy plate|lim /.test(j)||b.profiles.includes('PLATE'))out.push('heavy_plate');if(/rhs|shs|chs|tube|tub|rohr|pipe/.test(j))out.push('tubes');if(/hea|heb|hem|ipe|ipn|upn|upe|angle|profil/.test(j))out.push('profiles');if(/bolt|anker|anchor|hardware|bulon/.test(j))out.push('hardware');return U(out)}
function supplierScore(s:any,caps:string[],grades:string[]){const sc=new Set(A(s.categories).map(N)),sg=new Set(A(s.grades).map(gb));let z=Number(s.importance||0)*2;for(const c of caps)if(sc.has(N(c)))z+=15;for(const g of U(grades.map(gb)))if(sg.size)z+=sg.has(g)?7:-10;if(caps.includes('fabrication')&&N(s.business_type).includes('fabric'))z+=8;return z}
async function supplierMaster(){const {data:p,error}=await db.from('partners').select('id,name,business_type,relation,categories,grades,certifications,class_approval,importance,stage').eq('stage','active').contains('relation',['supplier']).order('importance',{ascending:false}).limit(500);if(error)throw error;const ids=A(p).map((x:any)=>x.id);let cs:any[]=[];if(ids.length){const r=await db.from('partner_contacts').select('partner_id,full_name,email,language,is_primary').in('partner_id',ids).not('email','is',null).order('is_primary',{ascending:false}).limit(2000);if(r.error)throw r.error;cs=r.data||[]}return A(p).map((x:any)=>({...x,contacts:cs.filter((c:any)=>c.partner_id===x.id)})).filter((x:any)=>x.contacts.length)}
async function projectEmails(pid:string){const {data,error}=await db.from('project_emails').select('gmail_message_id,gmail_thread_id,direction,from_email,from_name,to_emails,cc_emails,subject,snippet,sent_at,gmail_url,has_attachments').eq('project_id',pid).order('sent_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}
async function context(p:any){const [m,b,d,r,o]=await Promise.all([projectEmails(p.id),db.from('bom_items').select('*').eq('project_id',p.id).order('created_at',{ascending:true}).limit(5000),db.from('project_attachment_links').select('id,attachment_name,analysis_status,analysis_method,analysis_confidence,bom_status,bom_applied_count,extracted_text,extracted_data,analyzed_at,created_at').eq('project_id',String(p.id)).order('analyzed_at',{ascending:false,nullsFirst:false}).limit(20),db.from('rfq_log').select('*').eq('project_id',p.id).order('created_at',{ascending:false}).limit(300),db.from('offers').select('id,supplier,created_at,price_kg,total_eur,total_amount,offer_ref,incoterms,cert').eq('project_id',p.id).order('created_at',{ascending:false}).limit(100)]);for(const x of[b,d,r,o])if(x.error)throw x.error;return{project:p,emails:m,bom:b.data||[],docs:d.data||[],rfqs:r.data||[],offers:o.data||[]}}
function supplierEmails(master:any[]){return new Set(master.flatMap((s:any)=>A(s.contacts).map((x:any)=>E(x.email))).filter(Boolean))}
function latestIncoming(c:any,master:any[]){const se=supplierEmails(master);for(const m of c.emails){if(N(m.direction)!=='incoming')continue;return{...m,sender_role:se.has(E(m.from_email))?'supplier':'client_or_other'}}return null}
function currentGuard(c:any,b:any){const p=c.project,op=N(p.operational_state),st=N(p.pipeline_stage),realOffer=c.offers.some((o:any)=>Number(o.price_kg||0)>0||Number(o.total_eur||o.total_amount||0)>0||T(o.offer_ref));return{terminal:TERMINAL.includes(N(p.status)),operational_state:op,pipeline_stage:st,wait_for_client:op==='wait_for_client',wait_for_supplier:op==='wait_for_supplier',execution:op==='execution'||/production|execution/.test(st),commercial_offer_exists:realOffer&&/pricing|client_offer|commercial/.test(st),bom_ready:b.rows>0,bom_needs_review:b.needs_review_rows>0}}
function stopEvidence(li:any){if(!li)return false;const txt=N(`${li.subject||''} ${li.snippet||''}`);return /\b(stop|hold|suspend|pause)\b.{0,100}\b(fabrication|production|manufactur|weld|assembly)\b|\b(fabrication|production|manufactur|weld|assembly)\b.{0,100}\b(stop|hold|suspend|pause)\b|ndal.{0,70}(prodh|fabrik)|zaustav.{0,70}(proizvod|izradu)|produktion.{0,70}(stop|halt)/i.test(txt)}
function simpleAck(li:any){if(!li)return false;const txt=N(`${li.subject||''} ${li.snippet||''}`);return /\b(thank you|thanks|received|receipt|acknowledge|noted|danke|hvala|primljeno)\b/.test(txt)&&!/\b(please|need|must|urgent|change|revise|stop|hold|price|deadline|offer|quote|ponud|rok|izmen|izmjen|molim)\b/.test(txt)}
function sanitize(raw:any,c:any,payload:any,master:any[]){const li=latestIncoming(c,master),g=currentGuard(c,bsum(c.bom)),names=new Set(A(payload.supplier_candidates).map((x:any)=>x.name));let x:any={action_required:!!raw?.action_required,priority:PRI.includes(T(raw?.priority))?T(raw.priority):'medium',category:CAT.includes(T(raw?.category))?T(raw.category):'other',summary:CL(raw?.summary,1200),workflow_intent:INTENT.includes(T(raw?.workflow_intent))?T(raw.workflow_intent):'review_required',confidence:Math.max(0,Math.min(100,Number(raw?.confidence||0))),required_capabilities:U(raw?.required_capabilities).filter((v:string)=>CAPS.includes(v)),required_grades:U(raw?.required_grades).map(validGrade).filter(Boolean),requirements:U(raw?.requirements).slice(0,20),risks:U(raw?.risks).slice(0,15),missing_information:U(raw?.missing_information).slice(0,15),recommended_supplier_names:U(raw?.recommended_supplier_names).filter((v:string)=>names.has(v)).slice(0,8),rfq_scope_lines:U(raw?.rfq_scope_lines).slice(0,15)};
const det=payload.deterministic||{};x.required_capabilities=U([...x.required_capabilities,...A(det.required_capabilities)]).filter((v:string)=>CAPS.includes(v));x.required_grades=U([...x.required_grades,...A(det.required_grades)]).map(validGrade).filter(Boolean);
const hasStop=stopEvidence(li),newAfterWait=!!(li&&W(li.sent_at)>W(c.project.operational_state_at));
if(g.terminal){x.action_required=false;x.workflow_intent='no_action';x.category='no_action';x.priority='low'}
else if(hasStop){x.action_required=true;x.priority='critical';x.category='production_change';x.workflow_intent=g.execution?'execution':x.workflow_intent;x.summary=x.summary||'Kërkohet ndalim i prodhimit/fabrikimit deri në sqarim ose dokumentacion të ri.'}
else{
 if(x.category==='production_change'){x.category=x.action_required?'technical_change':'no_action';if(x.priority==='critical')x.priority='high'}
 if(g.wait_for_client&&!newAfterWait){x.action_required=false;x.workflow_intent='await_client';x.category=simpleAck(li)?'acknowledgement':'no_action';x.priority='low'}
 if(g.wait_for_supplier&&!newAfterWait){x.action_required=false;x.workflow_intent='await_supplier';x.category='no_action';x.priority='low'}
 if(li?.sender_role==='supplier'&&x.category==='client_request')x.category='supplier_update';
 if(simpleAck(li)){x.action_required=false;x.category='acknowledgement';if(g.wait_for_client)x.workflow_intent='await_client'}
}
return{result:x,latest_incoming:li,guard:g}}
function selectSuppliers(result:any,payload:any){const pref=new Set(A(result.recommended_supplier_names)),req=A(result.required_grades).map(gb),caps=A(result.required_capabilities);return A(payload.supplier_candidates).map((s:any)=>({...s,combined_score:Number(s.deterministic_score||0)+(pref.has(s.name)?40:0)})).filter((s:any)=>{const sc=A(s.categories).map(N),sg=A(s.grades).map(gb);if(caps.includes('fabrication')&&!sc.includes('fabrication'))return false;if(!caps.includes('fabrication')&&caps.length&&!caps.some((k:string)=>sc.includes(N(k))))return false;if(req.length&&sg.length&&req.some((g:string)=>!sg.includes(g)))return false;return true}).sort((a:any,b:any)=>b.combined_score-a.combined_score).slice(0,caps.includes('fabrication')?4:6)}
function lang(v:any){const n=N(v);if(['sq','albanian'].includes(n))return'sq';if(['sr','bs','hr','serbian','bosnian','croatian'].includes(n))return'sr';if(['de','german','deutsch'].includes(n))return'de';return'en'}
function projectLabel(p:any){let n=T(p.name)||'Projekt',c=T(p.client);if(c&&N(n).startsWith(N(c)))n=n.slice(c.length).replace(/^\s*[-–—|:]\s*/,'').trim()||n;return n}
function rfqSubject(p:any,l:string){const n=projectLabel(p);return l==='de'?`Anfrage | ${n}`:l==='sr'?`Zahtev za ponudu | ${n}`:l==='sq'?`Kerkese per oferte | ${n}`:`RFQ | ${n}`}
function rfqBody(p:any,ct:any,b:any,result:any){const l=lang(ct.language),who=T(ct.full_name).split(/\s+/)[0]||'',pr=projectLabel(p),doc=T(p.drive_folder_url)||(p.drive_folder_id?`https://drive.google.com/drive/folders/${T(p.drive_folder_id)}`:'[Shto linkun e dokumentacionit]'),qty=b.kg>0?`\nBOM total i regjistruar ne PPPP: ${b.kg.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})} kg.`:'',scope=A(result.rfq_scope_lines).length?`\n\nScope / sqarime nga PPPP:\n- ${A(result.rfq_scope_lines).join('\n- ')}`:'';if(l==='de')return`Guten Tag${who?` ${who}`:''},\n\nunser Kunde hat uns um ein Angebot fuer die Stahlkonstruktion des folgenden Projekts gebeten:\n${pr}\n\nProjektdokumentation:\n${doc}${qty}${scope}\n\nBitte senden Sie uns Ihr Angebot mit Material + Fertigung, erforderlicher Oberflaechenbehandlung, Transport, Lieferzeit, Incoterm und Zahlungsbedingungen. Unklarheiten oder technische Abweichungen bitte eindeutig kennzeichnen.\n\nMit freundlichen Gruessen\nArianit Vllahiu\nPRISTEEL Sh.p.k.\nsales@prissteel.com\n+383 44 244 699`;if(l==='sr')return`Postovani${who?` ${who}`:''},\n\nnas klijent je od nas zatrazio ponudu za celicnu konstrukciju za sledeci projekat:\n${pr}\n\nProjektnu dokumentaciju mozete preuzeti ovde:\n${doc}${qty}${scope}\n\nMolimo dostavite ponudu sa materijalom + izradom, potrebnom povrsinskom zastitom, transportom, rokom isporuke, Incotermom i uslovima placanja. Sve nejasnoce ili tehnicka odstupanja jasno navedite.\n\nSrdacan pozdrav,\nArianit Vllahiu\nPRISTEEL Sh.p.k.\nsales@prissteel.com\n+383 44 244 699`;if(l==='sq')return`Pershendetje${who?` ${who}`:''},\n\nBleresi yne na ka kerkuar oferte per konstruksionin e celikut per projektin:\n${pr}\n\nDokumentacioni i projektit:\n${doc}${qty}${scope}\n\nJu lutem dergoni oferten me material + prodhim, trajtimin siperfaqesor te kerkuar, transportin, afatin e dorezimit, Incoterm dhe kushtet e pageses. Cdo paqartesi ose devijim teknik shenojeni qarte.\n\nGjithe te mirat,\nArianit Vllahiu\nPRISTEEL Sh.p.k.\nsales@prissteel.com\n+383 44 244 699`;return`Hello${who?` ${who}`:''},\n\nour client requested a quotation for the steel structure of the following project:\n${pr}\n\nProject documentation:\n${doc}${qty}${scope}\n\nPlease provide your quotation including material + fabrication, required surface treatment, transport, delivery time, Incoterm and payment terms. Please identify any ambiguity or technical deviation clearly.\n\nKind regards,\nArianit Vllahiu\nPRISTEEL Sh.p.k.\nsales@prissteel.com\n+383 44 244 699`}
async function taskUpsert(row:any){const z=await db.from('tasks').upsert(row,{onConflict:'source,source_ref'});if(z.error)throw z.error;const q=await db.from('tasks').select('id,title,status,source_ref').eq('source',row.source).eq('source_ref',row.source_ref).limit(1);if(q.error)throw q.error;return A(q.data)[0]||null}
async function actionTask(c:any,result:any,li:any){if(!result.action_required||!li||W(li.sent_at)<Date.now()-30*86400000)return null;const sourceRef=`semantic:email:${li.gmail_message_id}`;const existing=await db.from('tasks').select('id,status,source_ref').eq('project_id',c.project.id).or(`source_ref.eq.${li.gmail_message_id},source_ref.eq.${sourceRef}`).limit(10);if(existing.error)throw existing.error;if(A(existing.data).some((x:any)=>!CLOSED.includes(N(x.status))))return A(existing.data)[0];const title=result.category==='production_change'?`URGJENT: ndalim / ndryshim prodhimi — ${c.project.name}`:`Shqyrto emailin: ${CL(result.summary,100)} — ${c.project.name}`,detail=`PPPP Local Semantic AI (${result.confidence}%): ${result.summary}\nKategoria: ${result.category}\nPrioriteti: ${result.priority}\nBurimi: ${li.subject||'(pa subjekt)'} · ${li.from_email||''}\nHuman gate: AI nuk ka derguar email dhe nuk ka bere angazhim komercial.`;return taskUpsert({project_id:c.project.id,title,detail,due_date:DAY(),priority:result.priority==='critical'?'e larte':result.priority==='high'?'larte':'normale',status:'hapur',source:'semantic_brain_auto',source_ref:sourceRef,category:li.sender_role==='supplier'?'furnitor':'klient',contact_email:li.from_email||null})}
async function procurement(c:any,result:any,payload:any,job:any,guard:any){const b=bsum(c.bom);if(guard.terminal||guard.wait_for_client||guard.wait_for_supplier||guard.execution||guard.commercial_offer_exists||!guard.bom_ready||result.workflow_intent!=='procurement_prepare')return{drafts:[],task:null};const sent=A(c.rfqs).filter((x:any)=>['sent','replied'].includes(N(x.status))&&W(x.sent_at||x.created_at)>=W(b.latest_at)-60000);if(sent.length)return{drafts:[],task:null};const selected=selectSuppliers(result,payload);if(!selected.length)return{drafts:[],task:null};const status=b.needs_review_rows>0?'draft_review':'draft',drafts:any[]=[];for(const s of selected){const ct=A(s.contacts).find((x:any)=>x.is_primary&&E(x.email))||A(s.contacts).find((x:any)=>E(x.email));if(!ct)continue;const mark=`PPPP_LOCAL_SEMANTIC_V2|${job.context_fingerprint}|${s.id}|${status}`;const old=A(c.rfqs).find((r:any)=>T(r.notes)===mark);if(old){drafts.push(old);continue}const row={project_id:c.project.id,project_name:c.project.name,supplier_name:s.name,supplier_email:E(ct.email),lang:lang(ct.language),subject:rfqSubject(c.project,lang(ct.language)),body:rfqBody(c.project,ct,b,result),status,notes:mark,sent_at:null},{data,error}=await db.from('rfq_log').insert(row).select('id,supplier_name,supplier_email,status,subject').limit(1);if(error)throw error;if(A(data)[0])drafts.push(A(data)[0])}let task=null;if(drafts.length){const ref=status==='draft_review'?`semantic:rfq-review:${c.project.id}`:`semantic:rfq-ready:${c.project.id}`,title=status==='draft_review'?`Kontrollo BOM para RFQ — ${c.project.name}`:`RFQ draftet jane gati — ${c.project.name}`,detail=status==='draft_review'?`PPPP ka pergatitur ${drafts.length} draft(e) RFQ, por ${b.needs_review_rows} pozicione BOM presin verifikim. Kontrollo BOM-in para hapjes ne Gmail.`:`PPPP ka pergatitur ${drafts.length} draft(e) RFQ nga BOM-i dhe analiza lokale semantike. Kontrolloji ne Prokurim para Gmail.`;task=await taskUpsert({project_id:c.project.id,title,detail,due_date:DAY(),priority:'larte',status:'hapur',source:'semantic_brain_auto',source_ref:ref,category:'furnitor'})}return{drafts,task}}
async function applyJob(job:any,master:any[]){const {data:p,error:pe}=await db.from('projects').select('*').eq('id',job.project_id).single();if(pe)throw pe;const c=await context(p),payload=job.payload||{},safe=sanitize(job.result||{},c,payload,master),result=safe.result,at=await actionTask(c,result,safe.latest_incoming),pr=await procurement(c,result,payload,job,safe.guard),analysis={semantic_local_version:2,context_fingerprint:job.context_fingerprint,model:job.model||'local',raw_model_result:job.result||{},guardrail:safe.guard,action_required:result.action_required,priority:result.priority,category:result.category,executive_summary:result.summary,workflow_intent_ai:result.workflow_intent,confidence:{score:result.confidence,reason:'Local model output validated and hard-overridden by deterministic PPPP rules using current project state and latest incoming evidence.'},requirements:result.requirements,risks:result.risks,missing_information:result.missing_information,procurement:{required_capabilities:result.required_capabilities,required_grades:result.required_grades,recommended_supplier_names:result.recommended_supplier_names,rfq_scope_lines:result.rfq_scope_lines,rfq_drafts:pr.drafts,task_id:pr.task?.id||null},action_task_id:at?.id||null};const ins=await db.from('project_analyses').insert({project_id:String(p.id),status:'complete',engine:'semantic_local_brain_v2',model:`local:${job.model||'qwen'}+deterministic-guard-v2`,analysis,source_manifest:payload.sources||[],source_counts:{emails:c.emails.length,documents:c.docs.length,bom_rows:c.bom.length,rfqs:c.rfqs.length},created_at:ISO()});if(ins.error)throw ins.error;const up=await db.from('semantic_ai_jobs').update({applied_at:ISO(),application_error:null}).eq('id',job.id);if(up.error)throw up.error;return{job_id:job.id,project_id:p.id,action_task:at?.id||null,rfq_drafts:pr.drafts.length,action_required:result.action_required,category:result.category}}
async function applyCompleted(limit:number,master:any[]){const {data,error}=await db.from('semantic_ai_jobs').select('*').eq('state','completed').is('applied_at',null).order('completed_at',{ascending:true}).limit(limit);if(error)throw error;const out:any[]=[];for(const j of data||[]){try{out.push(await applyJob(j,master))}catch(e){await db.from('semantic_ai_jobs').update({application_error:CL((e as any)?.message||e,3000)}).eq('id',j.id);out.push({job_id:j.id,error:String((e as any)?.message||e)})}}return out}
async function makePayload(c:any,master:any[]){const b=bsum(c.bom),caps=capabilities(c.project,b,c.docs),cands=master.map((s:any)=>({...s,deterministic_score:supplierScore(s,caps,b.grades)})).filter((s:any)=>s.deterministic_score>0).sort((a:any,b:any)=>b.deterministic_score-a.deterministic_score).slice(0,12),li=latestIncoming(c,master),guard=currentGuard(c,b),sources:any[]=[{id:'P1',type:'project',label:c.project.name,date:c.project.updated_at,text:CL(c.project.notes,1800)}];c.emails.slice(0,8).forEach((m:any,i:number)=>sources.push({id:`E${i+1}`,type:'email',label:m.subject,date:m.sent_at,text:CL(m.snippet,900),meta:{direction:m.direction,from:m.from_email,to:m.to_emails}}));c.docs.filter((x:any)=>['analyzed','complete'].includes(N(x.analysis_status))).slice(0,5).forEach((d:any,i:number)=>sources.push({id:`D${i+1}`,type:'document',label:d.attachment_name,date:d.analyzed_at||d.created_at,text:CL(d.extracted_text||JSON.stringify(d.extracted_data||{}),1800)}));return{worker_payload_version:2,system:SYSTEM,response_schema:SCHEMA,guard,bom:b,deterministic:{required_capabilities:caps,required_grades:b.grades},supplier_candidates:cands.map((s:any)=>({id:s.id,name:s.name,business_type:s.business_type,categories:s.categories,grades:s.grades,certifications:s.certifications,class_approval:s.class_approval,importance:s.importance,deterministic_score:s.deterministic_score,contacts:s.contacts})),meta:{latest_incoming:li?{gmail_message_id:li.gmail_message_id,subject:li.subject,snippet:li.snippet,sent_at:li.sent_at,from_email:li.from_email,sender_role:li.sender_role}:null},context:{project:{id:c.project.id,name:c.project.name,client:c.project.client,status:c.project.status,pipeline_stage:c.project.pipeline_stage,operational_state:c.project.operational_state,operational_state_at:c.project.operational_state_at,location:c.project.location,deadline:c.project.deadline,deal_type:c.project.deal_type},current_rfqs:c.rfqs.slice(0,10).map((r:any)=>({supplier_name:r.supplier_name,status:r.status,sent_at:r.sent_at,replied_at:r.replied_at,subject:r.subject})),supplier_offers:c.offers.filter((o:any)=>Number(o.price_kg||0)>0||Number(o.total_eur||o.total_amount||0)>0||T(o.offer_ref)).slice(0,6).map((o:any)=>({supplier:o.supplier,offer_ref:o.offer_ref,created_at:o.created_at,incoterms:o.incoterms,cert:o.cert}))},sources}}
async function enqueue(p:any,master:any[]){const c=await context(p),payload=await makePayload(c,master),fp=await hash(JSON.stringify({v:2,p:[p.id,p.updated_at,p.last_activity_at,p.last_email_at,p.operational_state,p.operational_state_at,p.pipeline_stage,p.status],e:c.emails.slice(0,15).map((x:any)=>[x.gmail_message_id,x.sent_at,x.direction,x.subject]),b:c.bom.map((x:any)=>[x.id,x.created_at,x.kg,x.grade,x.profile,x.needs_review]).slice(-500),d:c.docs.slice(0,12).map((x:any)=>[x.id,x.analysis_status,x.analyzed_at,x.bom_status,x.bom_applied_count]),r:c.rfqs.slice(0,25).map((x:any)=>[x.id,x.status,x.sent_at,x.replied_at,x.supplier_email])}));const existing=await db.from('semantic_ai_jobs').select('id,state').eq('project_id',p.id).eq('context_fingerprint',fp).limit(1);if(existing.error)throw existing.error;if(A(existing.data).length)return{project_id:p.id,name:p.name,fingerprint:fp,queued:false,state:A(existing.data)[0].state};await db.from('semantic_ai_jobs').update({state:'superseded',error:'Superseded by newer project context'}).eq('project_id',p.id).in('state',['pending','failed']);const row={project_id:p.id,context_fingerprint:fp,state:'pending',payload,attempts:0},{data,error}=await db.from('semantic_ai_jobs').insert(row).select('id,state,created_at').limit(1);if(error)throw error;return{project_id:p.id,name:p.name,fingerprint:fp,queued:!!A(data)[0],state:A(data)[0]?.state||'pending'}}
async function run(req:Request){const u=new URL(req.url),limit=Math.max(1,Math.min(30,Number(u.searchParams.get('limit')||10))),master=await supplierMaster(),applied=await applyCompleted(20,master),cutoff=new Date(Date.now()-45*86400000).toISOString(),q=await db.from('projects').select('*').not('status','is',null).or(`last_activity_at.gte.${cutoff},last_email_at.gte.${cutoff},updated_at.gte.${cutoff}`).order('last_activity_at',{ascending:false,nullsFirst:false}).limit(120);if(q.error)throw q.error;const projects=A(q.data).filter((p:any)=>!TERMINAL.includes(N(p.status))).slice(0,limit),queued:any[]=[];for(const p of projects){try{queued.push(await enqueue(p,master))}catch(e){queued.push({project_id:p.id,name:p.name,error:String((e as any)?.message||e)})}}return{ok:true,version:2,applied,queued,supplier_master:master.length}}
Deno.serve(async req=>{if(!(await auth(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:JSON_HEADERS});try{return new Response(JSON.stringify(await run(req)),{headers:JSON_HEADERS})}catch(e){return new Response(JSON.stringify({ok:false,error:String((e as any)?.message||e)}),{status:500,headers:JSON_HEADERS})}});
