import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SA_JSON=Deno.env.get("GOOGLE_SA_JSON")!;
const GMAIL_USER=Deno.env.get("GMAIL_USER")!;
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-pppp-cron-secret","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json"};

function s(v:any){return String(v??"").trim();}
function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pem(p:string){const x=p.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(x),b=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)b[i]=bin.charCodeAt(i);return b.buffer;}
let token:{v:string,exp:number}|null=null;
async function googleToken(){const now=Math.floor(Date.now()/1000);if(token&&token.exp>now+60)return token.v;const sa=JSON.parse(SA_JSON),head={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope:'https://www.googleapis.com/auth/gmail.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},u=`${b64url(JSON.stringify(head))}.${b64url(JSON.stringify(claim))}`,key=await crypto.subtle.importKey('pkcs8',pem(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(u))),jwt=`${u}.${b64url(sig)}`,r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),j=await r.json();if(!r.ok)throw new Error(`Google token ${r.status}: ${JSON.stringify(j).slice(0,300)}`);token={v:j.access_token,exp:now+(j.expires_in||3600)};return token.v;}
async function gmail(id:string){const t=await googleToken(),r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/messages/${encodeURIComponent(id)}?format=full`,{headers:{Authorization:`Bearer ${t}`}}),txt=await r.text();if(!r.ok)throw new Error(`Gmail ${r.status}: ${txt.slice(0,300)}`);return JSON.parse(txt);}
async function authorized(req:Request){const provided=req.headers.get('x-pppp-cron-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided});return !error&&data===true;}
function header(headers:any[],name:string){return s((headers||[]).find((x:any)=>s(x?.name).toLowerCase()===name.toLowerCase())?.value);}
type Meta={attachment_id:string;attachment_name:string;mime_type:string|null;size_bytes:number|null};
function collect(part:any,out:Meta[]=[]){if(!part)return out;const filename=s(part.filename),aid=s(part.body?.attachmentId),mime=s(part.mimeType)||null,disp=header(part.headers,'Content-Disposition'),cid=header(part.headers,'Content-ID');const inline=/(?:^|;)\s*inline\b/i.test(disp)||(!/attachment/i.test(disp)&&!!cid&&String(mime||'').toLowerCase().startsWith('image/'));if(filename&&aid&&!inline)out.push({attachment_id:aid,attachment_name:filename,mime_type:mime,size_bytes:Number(part.body?.size)||null});for(const c of part.parts||[])collect(c,out);return out;}
function uniqueMeta(full:any){const seen=new Set<string>(),out:Meta[]=[];for(const x of collect(full?.payload,[])){const k=`${x.attachment_id}|${x.attachment_name}`;if(seen.has(k))continue;seen.add(k);out.push(x);}return out;}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out=new Array<R>(items.length);let cur=0;async function worker(){while(true){const i=cur++;if(i>=items.length)return;out[i]=await fn(items[i]);}}await Promise.all(Array.from({length:Math.min(limit,Math.max(1,items.length))},()=>worker()));return out;}
type Pair={project_id:string;gmail_message_id:string;gmail_thread_id:string|null;sent_at:string|null};
async function candidates(limit:number,forceMessageId=''){const max=Math.min(200,Math.max(1,Math.floor(Number(limit)||40)));const {data:emails,error:ee}=await db.from('project_emails').select('project_id,gmail_message_id,gmail_thread_id,sent_at').not('gmail_message_id','is',null).order('sent_at',{ascending:false}).limit(5000);if(ee)throw ee;const {data:links,error:le}=await db.from('project_email_links').select('project_id,gmail_message_id,gmail_thread_id').not('project_id','is',null).not('gmail_message_id','is',null).limit(10000);if(le)throw le;const byMail=new Map<string,any>();for(const e of emails||[])byMail.set(s(e.gmail_message_id),e);const pairs=new Map<string,Pair>();for(const e of emails||[]){if(!e.project_id||!e.gmail_message_id)continue;const p={project_id:s(e.project_id),gmail_message_id:s(e.gmail_message_id),gmail_thread_id:s(e.gmail_thread_id)||null,sent_at:s(e.sent_at)||null};pairs.set(`${p.project_id}|${p.gmail_message_id}`,p);}for(const l of links||[]){if(!l.project_id||!l.gmail_message_id)continue;const e=byMail.get(s(l.gmail_message_id));const p={project_id:s(l.project_id),gmail_message_id:s(l.gmail_message_id),gmail_thread_id:s(l.gmail_thread_id)||s(e?.gmail_thread_id)||null,sent_at:s(e?.sent_at)||null};pairs.set(`${p.project_id}|${p.gmail_message_id}`,p);}let all=[...pairs.values()].sort((a,b)=>Date.parse(b.sent_at||'1970-01-01')-Date.parse(a.sent_at||'1970-01-01'));if(forceMessageId)all=all.filter(x=>x.gmail_message_id===forceMessageId);if(!all.length)return[];if(forceMessageId)return all.slice(0,max);const {data:scans,error:se}=await db.from('project_attachment_scan_state').select('project_id,gmail_message_id').limit(20000);if(se)throw se;const done=new Set((scans||[]).map((x:any)=>`${s(x.project_id)}|${s(x.gmail_message_id)}`));return all.filter(x=>!done.has(`${x.project_id}|${x.gmail_message_id}`)).slice(0,max);}
async function run(limit=40,forceMessageId=''){const pairs=await candidates(limit,forceMessageId),ids=[...new Set(pairs.map(x=>x.gmail_message_id))];if(!pairs.length)return{candidates:0,messages_fetched:0,pairs_scanned:0,rows_registered:0,no_downloadable:0,truth_corrected:0,failed:0};const results=await mapLimit(ids,6,async(id)=>{try{const full=await gmail(id);return{id,full,meta:uniqueMeta(full),error:null};}catch(e){return{id,full:null,meta:[] as Meta[],error:String(e)}}});const byId=new Map(results.map(x=>[x.id,x]));let rowsRegistered=0,noDownloadable=0,truthCorrected=0,pairsScanned=0,failed=0;const errors:any[]=[];for(const r of results){if(r.error){failed++;errors.push({gmail_message_id:r.id,error:r.error});continue;}const has=r.meta.length>0;const {data:changed,error:ue}=await db.from('project_emails').update({has_attachments:has,updated_at:new Date().toISOString()}).eq('gmail_message_id',r.id).neq('has_attachments',has).select('gmail_message_id');if(ue)throw ue;truthCorrected+=(changed||[]).length;}
for(const p of pairs){const r=byId.get(p.gmail_message_id);if(!r||r.error)continue;const now=new Date().toISOString(),meta=r.meta;if(meta.length){const rows=meta.map(x=>({gmail_message_id:p.gmail_message_id,gmail_thread_id:s(r.full?.threadId)||p.gmail_thread_id,attachment_id:x.attachment_id,attachment_name:x.attachment_name,project_id:p.project_id,drive_file_id:null,link_method:'server-reconcile-v1',attachment_mime_type:x.mime_type,attachment_size_bytes:x.size_bytes,updated_at:now}));const {data,error}=await db.from('project_attachment_links').upsert(rows,{onConflict:'gmail_message_id,attachment_id,project_id',ignoreDuplicates:true}).select('id');if(error)throw error;rowsRegistered+=(data||[]).length;}else noDownloadable++;const {error:se}=await db.from('project_attachment_scan_state').upsert({project_id:p.project_id,gmail_message_id:p.gmail_message_id,gmail_thread_id:s(r.full?.threadId)||p.gmail_thread_id,outcome:meta.length?'registered':'no_downloadable',attachment_count:meta.length,scan_method:'server-reconcile-v1',scanned_at:now},{onConflict:'project_id,gmail_message_id'});if(se)throw se;pairsScanned++;}
return{candidates:pairs.length,messages_fetched:ids.length,pairs_scanned:pairsScanned,rows_registered:rowsRegistered,no_downloadable:noDownloadable,truth_corrected:truthCorrected,failed,errors:errors.slice(0,10)};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(!(await authorized(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:H});try{const u=new URL(req.url);let body:any={};if(req.method==='POST')try{body=await req.json();}catch{}const limit=Number(u.searchParams.get('limit')||body.limit||40),messageId=s(u.searchParams.get('message_id')||body.message_id);const res=await run(limit,messageId);return new Response(JSON.stringify({ok:true,...res}),{headers:H});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:H});}});
