import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')||'';
const GMAIL_USER=(Deno.env.get('GMAIL_USER')||'').toLowerCase();
const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')||'';
const REGISTRY='pppp_opportunity_outreach_registry_v1';
const VERSION='pppp-opportunity-draft-register-v1';
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const text=(v:unknown,max=4000)=>String(v==null?'':v).trim().slice(0,max);
const email=(v:unknown)=>text(v,320).toLowerCase();
const isUuid=(v:unknown)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(text(v,80));
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Cache-Control':'no-store'}});

function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function gmailToken(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;if(!SA_JSON||!GMAIL_USER)throw new Error('gmail_service_account_missing');const sa=JSON.parse(SA_JSON),header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope:'https://www.googleapis.com/auth/gmail.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});const body=await r.json();if(!r.ok)throw new Error(`gmail_token_${r.status}`);cachedToken={token:body.access_token,exp:now+(body.expires_in||3600)};return cachedToken.token;}
async function currentUser(auth:string){if(!ANON_KEY)throw new Error('supabase_anon_key_missing');const client=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser();if(error||!data?.user)throw new Error('unauthorized');return data.user;}
function header(m:any,name:string){return text((m?.payload?.headers||[]).find((h:any)=>String(h?.name||'').toLowerCase()===name.toLowerCase())?.value,1000);}
async function gmailDraftMeta(draftId:string,messageId:string){try{const tk=await gmailToken();if(draftId){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts/${encodeURIComponent(draftId)}?format=metadata`,{headers:{Authorization:`Bearer ${tk}`}});if(r.ok){const d=await r.json();return d?.message||null;}}if(messageId){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/messages/${encodeURIComponent(messageId)}?format=metadata`,{headers:{Authorization:`Bearer ${tk}`}});if(r.ok)return await r.json();}}catch(e){console.warn(VERSION,'gmail metadata',e);}return null;}
async function findOrCreateAction(tender:any,recipient:string,subject:string){const existing=await db.from('pppp_opportunity_actions').select('*').eq('tender_watch_id',tender.id).eq('target_email',recipient).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(existing.error)throw existing.error;if(existing.data)return existing.data;const key=`manual_tender_outreach:${tender.id}:${recipient}`;const prior=await db.from('pppp_opportunity_actions').select('*').eq('action_key',key).maybeSingle();if(prior.error)throw prior.error;if(prior.data)return prior.data;const p=tender.payload&&typeof tender.payload==='object'?tender.payload:{},company=text(p?.winner?.name||p?.winner_name||tender.authority,500)||null;const ins=await db.from('pppp_opportunity_actions').insert({tender_watch_id:tender.id,action_key:key,action_type:'manual_tender_outreach_draft',route:'MANUAL_TENDER_OUTREACH',status:'draft_review',target_company:company,target_email:recipient,subject_hint:subject||null,draft_brief:'Draft i krijuar manualisht në Gmail nga PPPP.',payload:{source:'manual_gmail_draft',human_send_required:true,gmail_auto_send:false}}).select('*').single();if(ins.error)throw ins.error;return ins.data;}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const auth=req.headers.get('Authorization')||'';if(!auth.toLowerCase().startsWith('bearer '))return json({ok:false,error:'unauthorized'},401);const user=await currentUser(auth);let body:any={};try{body=await req.json();}catch{}const tenderId=text(body?.tender_id,80),recipient=email(body?.recipient_email),draftId=text(body?.gmail_draft_id,500),messageId=text(body?.gmail_message_id,500),subject=text(body?.subject,1000),createdAt=text(body?.created_at,80)||new Date().toISOString();if(!isUuid(tenderId))return json({ok:false,error:'valid_tender_id_required'},400);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient))return json({ok:false,error:'valid_recipient_email_required'},400);if(!draftId&&!messageId)return json({ok:false,error:'gmail_draft_identity_required'},400);const tq=await db.from('kek_tender_watch').select('id,title,authority,payload').eq('id',tenderId).maybeSingle();if(tq.error)throw tq.error;if(!tq.data)return json({ok:false,error:'tender_not_found'},404);const existing=await db.from(REGISTRY).select('*').eq('tender_watch_id',tenderId).eq('recipient_email',recipient).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(existing.error)throw existing.error;const meta=await gmailDraftMeta(draftId,messageId),threadId=text(body?.gmail_thread_id||meta?.threadId,500),actualMessageId=text(messageId||meta?.id,500);let row=existing.data;if(row){if(row.status!=='sent'){const upd=await db.from(REGISTRY).update({status:'draft_created',gmail_draft_id:draftId||row.gmail_draft_id||null,gmail_draft_message_id:actualMessageId||row.gmail_draft_message_id||null,gmail_thread_id:threadId||row.gmail_thread_id||null,draft_created_at:createdAt,last_checked_at:new Date().toISOString(),last_error:null,subject:subject||header(meta,'Subject')||row.subject||null,generator:VERSION,updated_at:new Date().toISOString(),payload:{...(row.payload||{}),source:'manual_gmail_draft',registered_by:user.id}}).eq('id',row.id).select('*').single();if(upd.error)throw upd.error;row=upd.data;}}
 else{const action=await findOrCreateAction(tq.data,recipient,subject),outreachId=crypto.randomUUID(),now=new Date().toISOString(),ins=await db.from(REGISTRY).insert({outreach_id:outreachId,action_id:action.id,action_key:action.action_key,tender_watch_id:tenderId,recipient_email:recipient,recipient_name:null,gmail_user:GMAIL_USER,gmail_draft_id:draftId||null,gmail_draft_message_id:actualMessageId||null,gmail_message_id:null,gmail_thread_id:threadId||null,rfc_message_id:`<manual.${outreachId}@prissteel.com>`,status:'draft_created',language:null,subject:subject||header(meta,'Subject')||null,mime_type:'text/html',html:true,human_send_required:true,gmail_auto_send:false,draft_created_at:createdAt,sent_at:null,last_checked_at:now,last_error:null,generator:VERSION,payload:{source:'manual_gmail_draft',registered_by:user.id},updated_at:now}).select('*').single();if(ins.error)throw ins.error;row=ins.data;}
 return json({ok:true,tender_id:tenderId,lifecycle:'draft',status:row.status,gmail_thread_id:row.gmail_thread_id||null,human_send_required:true,gmail_auto_send:false,version:VERSION});}catch(e){const msg=text((e as any)?.message||e,1000),status=msg==='unauthorized'?401:500;console.error(VERSION,e);return json({ok:false,error:msg,human_send_required:true,gmail_auto_send:false},status);}});
