/* Private project workbook. Loaded only on an explicit table action, never at startup. */
import * as D from './data.mjs?v=20261008-documents1';
import {esc} from './document-models.mjs?v=20261008-documents1';
export const TRACKER_NAME='SPIE_TenneT_Master_Commercial_and_Order_Tracker_v2_AUDITED.xlsx';
const SOURCE='https://chatgpt.com/api/library/files/libfile_37109f01fa188191990fe8e01e591809/download';
const MIME='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const MAX_BYTES=10*1024*1024,PAGE=150;
let dialog=null,book=null,source=null,selected=0,page=0,query='',busy=false,folder='',sessionToken='',parserPromise=null;
export function action(){return '<button class="btn" data-tracker>Tabela komerciale dhe e porosive</button>';}
export function resolveTracker(files,projectFolder){
 return files.filter(f=>(f.name||f.title)===TRACKER_NAME&&(!f.parents||f.parents.includes(projectFolder))&&!f.trashed).sort((a,b)=>String(b.modifiedTime||b.updated_at||'').localeCompare(String(a.modifiedTime||a.updated_at||'')));
}
function google(){if(D.session()?.access_token!==sessionToken)throw new Error('Sesioni ndryshoi. Rihap tabelën.');const g=D.googleSession('drive');if(!g)throw new Error('Lidh Google Drive në PPPP për tabelën e projektit.');return g;}
async function drive(path,options={}){const g=google(),r=await fetch('https://www.googleapis.com/drive/v3/'+path,{...options,headers:{Authorization:'Bearer '+g.token,...options.headers},signal:AbortSignal.timeout(25000)});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error('Drive '+r.status+': '+(x.error?.message||'Leximi nuk u konfirmua.'));}google();return r;}
async function parser(){if(window.XLSX)return window.XLSX;if(!parserPromise)parserPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';s.onload=()=>window.XLSX?resolve(window.XLSX):reject(new Error('Lexuesi Excel nuk u ngarkua.'));s.onerror=()=>reject(new Error('Lexuesi Excel nuk u ngarkua.'));document.head.append(s);}).catch(e=>{parserPromise=null;throw e;});return parserPromise;}
function status(message){if(dialog)dialog.querySelector('[data-tracker-status]').textContent=message;}
export function worksheetRows(X,worksheet){if(!worksheet)return [];const ref=worksheet['!ref'];if(!ref)return [];const range=X.utils.decode_range(ref);if(range.e.c>100||range.e.r>50000)throw new Error('Fleta tejkalon kufirin e pamjes (101 kolona / 50001 rreshta).');return X.utils.sheet_to_json(worksheet,{header:1,raw:false,defval:'',blankrows:false});}
export function tableHtml(rows){return '<table><tbody>'+rows.map(row=>'<tr>'+row.map(value=>'<td>'+esc(value)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function render(){if(!book||!dialog)return;const names=book.SheetNames,rows=worksheetRows(window.XLSX,book.Sheets[names[selected]]),filtered=query?rows.filter(r=>r.some(v=>String(v).toLocaleLowerCase().includes(query))):rows;page=Math.min(page,Math.max(0,Math.ceil(filtered.length/PAGE)-1));
 const box=dialog.querySelector('[data-tracker-content]');box.innerHTML='<div class="tracker-toolbar"><label>Fleta<select data-tracker-sheet>'+names.map((name,i)=>'<option value="'+i+'" '+(i===selected?'selected':'')+'>'+esc(name)+'</option>').join('')+'</select></label><label>Kërko në fletë<input data-tracker-search type="search" value="'+esc(query)+'"></label></div><p class="muted small">'+esc(source?.name||TRACKER_NAME)+' · '+filtered.length+' rreshta · Vlerat dhe formulat e ruajtura në Excel. Gjendja në tabelë kërkon kontroll kundrejt regjistrave PPPP.</p><div class="table-wrap tracker-grid">'+tableHtml(filtered.slice(page*PAGE,(page+1)*PAGE))+'</div><div class="document-actions"><button class="btn" data-tracker-prev '+(page===0?'disabled':'')+'>Më parë</button><span>Faqja '+(page+1)+' / '+Math.max(1,Math.ceil(filtered.length/PAGE))+'</span><button class="btn" data-tracker-next '+((page+1)*PAGE>=filtered.length?'disabled':'')+'>Më tej</button>'+(source?.id?'<a class="evidence-link" href="https://drive.google.com/file/d/'+encodeURIComponent(source.id)+'/view" target="_blank" rel="noopener noreferrer">Hap Excel-in për ndryshime</a>':'')+'</div>';
 box.querySelector('[data-tracker-sheet]').onchange=e=>{selected=Number(e.target.value);page=0;query='';render();};box.querySelector('[data-tracker-search]').oninput=e=>{query=e.target.value.toLocaleLowerCase();page=0;const focus=e.target.selectionStart;render();const input=box.querySelector('[data-tracker-search]');input.focus();input.setSelectionRange(focus,focus);};box.querySelector('[data-tracker-prev]').onclick=()=>{page--;render();};box.querySelector('[data-tracker-next]').onclick=()=>{page++;render();};
}
async function readBook(bytes,metadata){if(bytes.byteLength>MAX_BYTES)throw new Error('Tabela tejkalon 10 MB.');const X=await parser();const parsed=X.read(bytes,{type:'array',cellDates:false,cellFormula:true});if(!parsed.SheetNames?.length)throw new Error('Skedari nuk përmban fletë Excel.');google();book=parsed;source=metadata;selected=0;page=0;query='';render();}
async function discover(){const q="'"+folder+"' in parents and trashed = false and name = '"+TRACKER_NAME+"'";const r=await drive('files?'+new URLSearchParams({q,fields:'files(id,name,mimeType,size,parents,modifiedTime),nextPageToken',pageSize:'10',orderBy:'modifiedTime desc'}));const list=await r.json();if(list.nextPageToken)throw new Error('Ka disa versione të tabelës; kontrollo dosjen Drive.');const found=resolveTracker(list.files||[],folder);if(found.length>1)throw new Error('Ka disa kopje të tabelës në dosjen SPIE. Zgjidh versionin në Drive përpara leximit.');return found[0]||null;}
async function load(){busy=true;try{status('Duke kërkuar tabelën në dosjen e SPIE.');const metadata=await discover();if(!metadata){status('Tabela nuk është ende në dosjen e SPIE. Zgjidh skedarin Excel për ta lidhur këtu.');return;}if(metadata.mimeType!==MIME)throw new Error('Burimi duhet të mbetet skedari origjinal Excel.');if(Number(metadata.size)>MAX_BYTES)throw new Error('Tabela tejkalon 10 MB.');const r=await drive('files/'+encodeURIComponent(metadata.id)+'?alt=media');await readBook(await r.arrayBuffer(),metadata);status('Tabela u lexua nga dosja private e SPIE.');dialog.querySelector('[data-tracker-upload]').hidden=true;}catch(e){status(e.message);}finally{busy=false;}}
async function upload(file){if(!file||busy)return;busy=true;const button=dialog.querySelector('[data-tracker-upload]');button.disabled=true;try{google();if(file.name!==TRACKER_NAME||file.size>MAX_BYTES)throw new Error('Zgjidh '+TRACKER_NAME+' (deri në 10 MB).');const existing=await discover();if(existing){status('Tabela ekziston në Drive. Rihap tabelën për ta lexuar; nuk u krijua kopje.');return;}const bytes=await file.arrayBuffer();await readBook(bytes,{name:file.name});
 const form=new FormData();form.append('metadata',new Blob([JSON.stringify({name:TRACKER_NAME,parents:[folder],appProperties:{pppp_project_id:D.PROJECT_ID,pppp_purpose:'spie_master_tracker'}})],{type:'application/json'}));form.append('file',new Blob([bytes],{type:MIME}),TRACKER_NAME);
 status('Duke ruajtur tabelën në dosjen e SPIE.');const g=google(),response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,parents',{method:'POST',headers:{Authorization:'Bearer '+g.token},body:form,signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Ngarkimi nuk u konfirmua. Rihap tabelën për kontroll përpara çdo riprovimi.');const created=await response.json();if(!created.id)throw new Error('Drive nuk ktheu identitetin e skedarit.');const verified=await(await drive('files/'+encodeURIComponent(created.id)+'?fields=id,name,mimeType,size,parents')).json();if(verified.name!==TRACKER_NAME||verified.mimeType!==MIME||Number(verified.size)!==file.size||!verified.parents?.includes(folder))throw new Error('Lidhja e skedarit me dosjen nuk u verifikua. Mos e ngarko përsëri.');source=verified;render();status('Tabela u ruajt dhe u verifikua në dosjen SPIE.');button.hidden=true;document.dispatchEvent(new CustomEvent('spie:tracker-uploaded'));}catch(e){status(e.message);}finally{busy=false;button.disabled=false;}}
export async function open(context){if(dialog){dialog.focus();return;}if(context?.data?.project?.id!==D.PROJECT_ID)throw new Error('Projekti SPIE nuk u verifikua.');folder=context.data.project.drive_folder_id;if(!/^[\w-]+$/.test(folder||''))throw new Error('Dosja Drive e projektit mungon.');sessionToken=D.session()?.access_token;book=null;source=null;
 dialog=document.createElement('dialog');dialog.className='project-tracker';dialog.innerHTML='<div class="document-editor-head"><h2>Tabela komerciale dhe e porosive · SPIE</h2><button class="btn" data-tracker-close>Mbyll</button></div><p data-tracker-status role="status"></p><div class="document-actions"><a class="evidence-link" href="'+SOURCE+'" target="_blank" rel="noopener noreferrer">Shkarko tabelën e ngarkuar</a><button class="btn" data-tracker-upload>Zgjidh Excel-in dhe ruaje te SPIE</button><input type="file" data-tracker-file accept=".xlsx" hidden></div><div data-tracker-content></div>';
 document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-tracker-close]').onclick=()=>{if(busy){status('Prit përfundimin e veprimit.');return;}dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.onclose=()=>{dialog.remove();dialog=null;book=null;source=null;};const input=dialog.querySelector('[data-tracker-file]');dialog.querySelector('[data-tracker-upload]').onclick=()=>input.click();input.onchange=()=>upload(input.files[0]);await load();}
