import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!;
const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')!;
const GMAIL_USER=Deno.env.get('GMAIL_USER')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const text=(v:any,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);
const safeHeader=(v:any)=>text(v,500).replace(/[\r\n]+/g,' ');
function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function bytesFromBase64(s:string){const bin=atob(s.replace(/\s+/g,''));const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function base64Lines(bytes:Uint8Array){let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));const s=btoa(bin);return s.match(/.{1,76}/g)?.join('\r\n')||s;}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function gmailToken(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;const sa=JSON.parse(SA_JSON),scope='https://www.googleapis.com/auth/gmail.compose',header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),data=await r.json();if(!r.ok)throw new Error(`Google token ${r.status}: ${JSON.stringify(data).slice(0,400)}`);cachedToken={token:data.access_token,exp:now+(data.expires_in||3600)};return cachedToken.token;}
function encodeSubject(s:string){const bytes=new TextEncoder().encode(s);let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return `=?UTF-8?B?${btoa(bin)}?=`;}
function greeting(contact:string,lang:string){const c=text(contact,120);if(lang==='de')return c?`Sehr geehrte/r ${c},`:'Sehr geehrte Damen und Herren,';if(lang==='sq')return c?`I nderuar ${c},`:'Të nderuar,';if(lang==='sr')return c?`Poštovani ${c},`:'Poštovani,';return c?`Dear ${c},`:'Dear Sir or Madam,';}
function bodyFor(doc:any){const st=doc.offer_state||{},lang=text(st.lang||'en',10).toLowerCase(),project=text(doc.project||st.proj,500),nr=text(doc.doc_nr,100);if(lang==='de')return `${greeting(st.con,lang)}\n\nanbei erhalten Sie unser Angebot ${nr} für ${project}.\n\nFür Rückfragen oder weitere Abstimmungen stehen wir Ihnen gerne zur Verfügung.\n\nMit freundlichen Grüßen\nPriSteel`;if(lang==='sq')return `${greeting(st.con,lang)}\n\nBashkëngjitur gjeni ofertën tonë ${nr} për ${project}.\n\nPër çdo sqarim ose koordinim të mëtejshëm, mbetemi në dispozicion.\n\nMe respekt,\nPriSteel`;if(lang==='sr')return `${greeting(st.con,lang)}\n\nu prilogu dostavljamo našu ponudu ${nr} za ${project}.\n\nZa sva dodatna pitanja ili usaglašavanja stojimo vam na raspolaganju.\n\nSrdačan pozdrav,\nPriSteel`;return `${greeting(st.con,lang)}\n\nPlease find attached our quotation ${nr} for ${project}.\n\nShould you need any clarification or further coordination, we remain at your disposal.\n\nBest regards,\nPriSteel`;}
function subjectFor(doc:any){const st=doc.offer_state||{},lang=text(st.lang||'en',10).toLowerCase(),project=text(doc.project||st.proj,300),nr=text(doc.doc_nr,100);if(lang==='de')return `Angebot ${nr} · ${project}`;if(lang==='sq')return `Oferta ${nr} · ${project}`;if(lang==='sr')return `Ponuda ${nr} · ${project}`;return `Quotation ${nr} · ${project}`;}
function mime(doc:any,pdf:Uint8Array,filename:string){const st=doc.offer_state||{},to=safeHeader(st.em),subject=encodeSubject(subjectFor(doc)),boundary=`pppp_${crypto.randomUUID().replace(/-/g,'')}`;return [`To: ${to}`,`Subject: ${subject}`,'MIME-Version: 1.0',`Content-Type: multipart/mixed; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit','',bodyFor(doc),'',`--${boundary}`,`Content-Type: application/pdf; name="${safeHeader(filename)}"`,'Content-Transfer-Encoding: base64',`Content-Disposition: attachment; filename="${safeHeader(filename)}"`,'',base64Lines(pdf),'',`--${boundary}--`,''].join('\r\n');}
async function putDraft(raw:string,existingId:string|null){const tk=await gmailToken(),payload={message:{raw:b64url(raw)}};if(existingId){const url=`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts/${encodeURIComponent(existingId)}`,r=await fetch(url,{method:'PUT',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify({id:existingId,...payload})}),data=await r.json();if(r.ok)return data;if(r.status!==404)throw new Error(`Gmail draft update ${r.status}: ${JSON.stringify(data).slice(0,600)}`);}const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts`,{method:'POST',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw new Error(`Gmail draft create ${r.status}: ${JSON.stringify(data).slice(0,600)}`);return data;}
async function currentUser(req:Request){const auth=req.headers.get('Authorization')||'',userDb=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}}}),{data,error}=await userDb.auth.getUser();if(error||!data.user)throw new Error('Authenticated user required');return data.user;}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({ok:false,error:'POST required'}),{status:405,headers:cors});try{const user=await currentUser(req),input=await req.json(),documentId=text(input.document_id,80),pdf64=text(input.pdf_base64,16000000),filename=safeHeader(input.filename||'PriSteel-Quotation.pdf');if(!documentId||!pdf64)throw new Error('document_id and pdf_base64 are required');if(pdf64.length>14000000)throw new Error('PDF payload too large');const {data:doc,error}=await db.from('documents_registry').select('id,project_id,doc_nr,project,client,offer_state,currency,total_amount,total_eur').eq('id',documentId).eq('series','QUO').maybeSingle();if(error)throw error;if(!doc)throw new Error('Quotation not found');const st:any=doc.offer_state||{},approval:any=st.pricing_approval||{};if(st.source!=='pppp-client-offer-finalization-v1'||st.human_pricing_approved!==true)throw new Error('Quotation has not passed the human pricing approval gate');if(String(approval.actor_user_id||'')!==String(user.id))throw new Error('Only the user who approved this pricing can generate its Gmail draft');if(!st.em)throw new Error('Client email is missing');const pdf=bytesFromBase64(pdf64);if(pdf.length<500||String.fromCharCode(...pdf.subarray(0,4))!=='%PDF')throw new Error('Invalid PDF payload');const raw=mime(doc,pdf,filename),draft=await putDraft(raw,st.gmail_draft_id||null),now=new Date().toISOString(),next={...st,pdf_status:'ready',pdf_filename:filename,pdf_bytes:pdf.length,pdf_generated_at:now,pdf_generator:'browser-html2pdf-v1',gmail_draft_id:draft.id,gmail_message_id:draft.message?.id||null,gmail_thread_id:draft.message?.threadId||null,gmail_draft_created_at:now,gmail_draft_generator:'pppp-client-offer-draft-generator-v2',gmail_draft_stale:false,pst_document_status:'gmail_draft_ready',revision_status:'draft_ready',human_send_required:true};const {error:updateError}=await db.from('documents_registry').update({offer_state:next}).eq('id',documentId);if(updateError)throw updateError;if(doc.project_id)await db.from('tasks').update({title:`Shqyrto dhe dërgo ofertën · ${doc.doc_nr}`,detail:`PDF-ja dhe Gmail draft-i janë gati për ${st.em}. Dokumenti: ${doc.doc_nr}.\n\nHuman gate: kontrollo PDF-në, tekstin e emailit, çmimin dhe kushtet komerciale; pastaj dërgoje vetë nga Gmail. PPPP nuk e dërgon automatikisht.`,status:'hapur',done_at:null,due_date:new Date().toISOString().slice(0,10)}).eq('project_id',doc.project_id).eq('source','client_offer_final_review_auto');return new Response(JSON.stringify({ok:true,document_id:doc.id,doc_nr:doc.doc_nr,gmail_draft_id:draft.id,gmail_message_id:draft.message?.id||null,gmail_thread_id:draft.message?.threadId||null,pdf_bytes:pdf.length,human_send_required:true}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e instanceof Error?e.message:e)}),{status:400,headers:cors});}});
