import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import * as XLSX from "npm:xlsx@0.18.5";
import mammoth from "npm:mammoth@1.9.1";
import pdfParse from "npm:pdf-parse@1.1.1";
import { unzipSync } from "npm:fflate@0.8.2";
import { Buffer } from "node:buffer";
import { analyzeText, classifyUnsupported, decodeBase64UrlBytes, extOf, mimeGuess, safeFileName, sha256Hex } from "./document-intelligence.mjs";

const SA_JSON=Deno.env.get("GOOGLE_SA_JSON")!,GMAIL_USER=Deno.env.get("GMAIL_USER")!,SUPABASE_URL=Deno.env.get("SUPABASE_URL")!,SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,BUCKET="project-source-files";
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-pppp-cron-secret","Access-Control-Allow-Methods":"POST, GET, OPTIONS"};
type L={id:number;gmail_message_id:string;gmail_thread_id:string|null;attachment_id:string;attachment_name:string|null;project_id:string;drive_file_id:string|null;storage_path?:string|null;analysis_status?:string|null;created_at?:string|null};
const cols="id,gmail_message_id,gmail_thread_id,attachment_id,attachment_name,project_id,drive_file_id,storage_path,analysis_status,created_at";
const ZIP_TYPES=new Set(['pdf','docx','xlsx','xls','csv','txt','md','json','xml','html','dxf','dwg']);

function b64url(input:Uint8Array|string){const bytes=typeof input==="string"?new TextEncoder().encode(input):input;let bin="";for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function pem(p:string){const x=p.replace(/-----BEGIN PRIVATE KEY-----/,"").replace(/-----END PRIVATE KEY-----/,"").replace(/\s+/g,"");const bin=atob(x),b=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)b[i]=bin.charCodeAt(i);return b.buffer;}
let token:{v:string;exp:number}|null=null;
async function gmailToken(){const now=Math.floor(Date.now()/1000);if(token&&token.exp>now+60)return token.v;const sa=JSON.parse(SA_JSON),head={alg:"RS256",typ:"JWT"},claim={iss:sa.client_email,sub:GMAIL_USER,scope:"https://www.googleapis.com/auth/gmail.readonly",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600},u=`${b64url(JSON.stringify(head))}.${b64url(JSON.stringify(claim))}`,key=await crypto.subtle.importKey("pkcs8",pem(sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(u))),jwt=`${u}.${b64url(sig)}`,r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:jwt})}),j=await r.json();if(!r.ok)throw new Error(`Google token ${r.status}: ${j?.error||"failed"}`);token={v:j.access_token,exp:now+(j.expires_in||3600)};return token.v;}
async function auth(req:Request){const provided=req.headers.get("x-pppp-cron-secret")||"";if(!provided)return false;const {data,error}=await db.rpc("gmail_tracker_cron_authorized",{provided});return !error&&data===true;}
async function gmail(path:string){const t=await gmailToken(),r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}${path}`,{headers:{Authorization:`Bearer ${t}`}}),x=await r.text();if(!r.ok)throw new Error(`Gmail ${r.status}: ${x.slice(0,400)}`);return x?JSON.parse(x):{};}

function collectParts(node:any,out:any[]=[]):any[]{if(!node)return out;const aid=String(node.body?.attachmentId||"").trim(),name=String(node.filename||"").trim();if(aid&&name)out.push(node);for(const c of node.parts||[])collectParts(c,out);return out;}
async function resolvePart(link:L,payload:any){const parts=collectParts(payload,[]),exact=parts.find((p:any)=>String(p.body?.attachmentId||"")===String(link.attachment_id));if(exact)return exact;const name=String(link.attachment_name||"").trim();if(!name)throw new Error("Attachment MIME part not found and filename missing");const same=parts.filter((p:any)=>String(p.filename||"").trim()===name);if(same.length===1)return same[0];if(!same.length)throw new Error(`Attachment not found by current MIME filename: ${name}`);const {data:siblings,error}=await db.from("project_attachment_links").select("id").eq("gmail_message_id",link.gmail_message_id).eq("project_id",link.project_id).eq("attachment_name",name).order("id",{ascending:true});if(error)throw error;const rows=siblings||[];if(rows.length!==same.length)throw new Error(`Ambiguous current MIME attachment mapping for ${name}: ${same.length} live parts vs ${rows.length} registered links`);const idx=rows.findIndex((x:any)=>Number(x.id)===Number(link.id));if(idx>=0&&same[idx])return same[idx];throw new Error(`Ambiguous current MIME attachment mapping for ${name}`);}
async function bytes(link:L){const full=await gmail(`/messages/${encodeURIComponent(link.gmail_message_id)}?format=full`),p=await resolvePart(link,full?.payload),liveId=String(p.body?.attachmentId||"");if(!liveId)throw new Error("Resolved attachment has no live Gmail attachment id");const a=await gmail(`/messages/${encodeURIComponent(link.gmail_message_id)}/attachments/${encodeURIComponent(liveId)}`),b=decodeBase64UrlBytes(String(a?.data||""));if(!b.length)throw new Error("Empty Gmail attachment");return {b,mime:mimeGuess(link.attachment_name||"",String(p.mimeType||"")),size:Number(a?.size||p.body?.size||b.length)||b.length};}

async function bucket(){const {data}=await db.storage.getBucket(BUCKET);if(data)return;const {error}=await db.storage.createBucket(BUCKET,{public:false,fileSizeLimit:30*1024*1024});if(error&&!/already exists/i.test(error.message))throw error;}
async function archive(link:L,b:Uint8Array,mime:string){await bucket();const path=`${link.project_id}/gmail/${link.gmail_message_id}/${link.id}-${safeFileName(link.attachment_name||`attachment-${link.id}`)}`,{error}=await db.storage.from(BUCKET).upload(path,b,{contentType:mime,upsert:false});if(error&&!/already exists|duplicate/i.test(error.message))throw error;return path;}

async function extract(b:Uint8Array,name:string,mime:string):Promise<any>{
  const e=extOf(name),m=String(mime||"").toLowerCase();
  try{
    if(e==='zip'||m.includes('zip')){
      if(b.length>15*1024*1024)return {text:'',method:'zip-guard-v1',status:'review',error:'ZIP exceeds the 15 MiB safe automatic intake limit.'};
      const files=unzipSync(b,{filter(file:any){const ex=extOf(file.name);return ZIP_TYPES.has(ex)&&Number(file.originalSize||0)<=10_000_000;}}),names=Object.keys(files).slice(0,60),out:string[]=[],pending:string[]=[];let total=0;
      for(const child of names){const data=files[child];total+=data.length;if(total>40*1024*1024){pending.push('Archive extraction stopped at 40 MiB total uncompressed safety limit.');break;}const ce=extOf(child);if(ce==='dwg'){pending.push(`${child}: DWG requires trusted CAD conversion`);continue;}const r=await extract(data,child,mimeGuess(child,''));if(String(r.text||'').trim())out.push(`ZIP ENTRY: ${child}\n${r.text}`);else if(!['unsupported'].includes(String(r.status||'')))pending.push(`${child}: ${r.error||r.status||'review required'}`);}
      return {text:out.join('\n\n').slice(0,120000),method:'zip-supported-files-v1',status:out.length?'extracted':pending.length?'review':'unsupported',error:pending.length?pending.join('\n').slice(0,4000):null,embedded_entries:names,embedded_pending:pending};
    }
    if(e==="pdf"||m.includes("pdf")){const p:any=await (pdfParse as any)(Buffer.from(b)),text=String(p?.text||"").slice(0,120000);return {text,method:"pdf-parse-v1",status:text.trim()?"extracted":"needs_ocr"};}
    if(e==="docx"||m.includes("wordprocessingml")){const p:any=await mammoth.extractRawText({buffer:Buffer.from(b)} as any),text=String(p?.value||"").slice(0,120000);return {text,method:"mammoth-v1",status:text.trim()?"extracted":"review"};}
    if(["xlsx","xls"].includes(e)||m.includes("spreadsheetml")||m==="application/vnd.ms-excel"){const wb=XLSX.read(Buffer.from(b),{type:"buffer"}),out:string[]=[];for(const s of wb.SheetNames.slice(0,20))out.push(`Sheet: ${s}\n${XLSX.utils.sheet_to_csv(wb.Sheets[s])}`);return {text:out.join("\n\n").slice(0,120000),method:"xlsx-v1",status:out.length?"extracted":"review"};}
    if(m.startsWith("text/")||["csv","txt","md","json","xml","html","dxf"].includes(e)||m==="application/json"||m==="application/xml"||m.includes("dxf"))return {text:new TextDecoder("utf-8",{fatal:false}).decode(b).slice(0,120000),method:e==="dxf"?"dxf-ascii-v1":"text-v1",status:"extracted"};
    const u=classifyUnsupported(name,mime);return {text:"",method:u.kind,status:u.status,error:u.reason};
  }catch(e2){return {text:"",method:`extract-error-${e||"file"}`,status:"retry",error:String(e2)};}
}
function std(f:any){return (f?.standards||[]).find((x:string)=>/EN\s*10025/i.test(x))||(f?.standards||[])[0]||null;}
function normDim(v:any){return String(v==null?'':v).toLowerCase().replace(/\bmm\b/g,'').replace(/[×*]/g,'x').replace(/\s+/g,'').replace(/,/g,'.');}
function normGrade(v:any){return String(v==null?'':v).toUpperCase().replace(/\s+/g,'');}
function semanticMatch(c:any,r:any){const pcs=Number(r.pcs!=null?r.pcs:r.sasia);if(Number.isFinite(Number(c.pcs))&&Number.isFinite(pcs)&&Number(c.pcs)!==pcs)return false;if(normGrade(c.grade)&&normGrade(r.grade)&&normGrade(c.grade)!==normGrade(r.grade))return false;if(c.profile==='PLATE')return normDim(c.dim)===normDim(r.dim||r.dimensionet);if(normGrade(c.profile)!==normGrade(r.profile))return false;return normDim(c.dim)===normDim(r.dim||r.dimensionet);}
async function bom(project:any,link:L,a:any){
  const candidates=(a?.auto_bom_candidates||[]).filter((x:any)=>x.complete&&Number(x.confidence)>=.96),result={inserted:0,already:[] as any[],conflicts:[] as any[]};if(!candidates.length)return result;
  const {data:existing,error:ee}=await db.from("bom_items").select("id,profile,dim,dimensionet,grade,pcs,sasia,kg,source_attachment_link_id,source_item_key").eq("project_id",project.id).limit(5000);if(ee)throw ee;
  const rows=existing||[],toInsert:any[]=[];
  for(const c of candidates){const exact=rows.find((r:any)=>Number(r.source_attachment_link_id)===Number(link.id)&&String(r.source_item_key||'')===String(c.source_item_key||''));if(exact){result.already.push({candidate:c,existing_id:exact.id,reason:'same_source'});continue;}const same=rows.find((r:any)=>semanticMatch(c,r));if(same){const ekg=Number(same.kg),ckg=Number(c.kg);if(ekg>0&&ckg>0){const pct=Math.abs(ekg-ckg)/ckg;if(pct>0.002){result.conflicts.push({source_locator:c.source_locator,existing_id:same.id,document_kg:ckg,existing_kg:ekg,difference_pct:+(pct*100).toFixed(3),dim:c.dim,grade:c.grade,pcs:c.pcs});continue;}}result.already.push({candidate:c,existing_id:same.id,reason:'semantic_match'});continue;}toInsert.push(c);}
  const base=Date.now()*1000,insertRows=toInsert.map((x:any,i:number)=>({id:base+i,project_id:project.id,project_name:project.name,pozicioni:`AUTO-${link.id}-${i+1}`,materiali:x.grade||null,dimensionet:[x.profile,x.dim].filter(Boolean).join(" "),sasia:x.pcs,kg_unit:x.kg_unit,profile:x.profile,dim:x.dim,grade:x.grade,std:std(a.facts),len_mm:x.len_mm,pcs:x.pcs,kg:x.kg,surface:(a.facts?.surface||[])[0]||"none",cert:(a.facts?.certificates||[])[0]||null,source_attachment_link_id:link.id,source_file_name:link.attachment_name,source_locator:x.source_locator,source_item_key:x.source_item_key,extraction_method:"document-intake-v2",extraction_confidence:x.confidence,auto_generated:true,needs_review:false}));if(insertRows.length){const {error}=await db.from("bom_items").insert(insertRows);if(error)throw error;result.inserted=insertRows.length;}return result;
}
async function task(project:any,link:L,reason:string,count=0){const {error}=await db.from("tasks").upsert({project_id:project.id,title:`Rishiko dokumentin teknik: ${safeFileName(link.attachment_name||"attachment")}`,detail:[reason,count?`${count} pozicione BOM kerkojne verifikim.`:"",`Project: ${project.name}`,`Attachment link #${link.id}`].filter(Boolean).join("\n"),due_date:new Date().toISOString().slice(0,10),priority:"larte",status:"hapur",source:"document_bom_review",source_ref:`ATTACHMENT:${link.id}`,category:"intern"},{onConflict:"source,source_ref",ignoreDuplicates:true});if(error)throw error;}
async function deferNonTechnical(link:L,status:string,method:string,reason:string){const now=new Date().toISOString(),{error}=await db.from('project_attachment_links').update({analysis_status:status,analysis_method:method,analysis_error:reason,updated_at:now}).eq('id',link.id);if(error)throw error;return {id:link.id,project_id:link.project_id,name:link.attachment_name,analysis_status:status,bom_status:'none',deferred:true};}

async function process(link:L,apply=true){
  const sourceName=String(link.attachment_name||'').trim();if(!apply)return {id:link.id,project_id:link.project_id,name:link.attachment_name,status:link.analysis_status};
  if(/^https?:\/\//i.test(sourceName))return await deferNonTechnical(link,'metadata_noise','url-like-attachment-name-v1','URL-like MIME part name; no technical binary intake attempted.');
  if(/\.(?:png|jpe?g|gif)$/i.test(sourceName))return await deferNonTechnical(link,'needs_vision','image-vision-pending-v1','Image attachment preserved in Gmail relation; technical vision extraction is not yet enabled.');
  const {data:project,error}=await db.from("projects").select("id,name").eq("id",link.project_id).maybeSingle();if(error||!project)throw error||new Error("Project not found");
  const g=await bytes(link),hash=await sha256Hex(g.b),path=link.storage_path||await archive(link,g.b,g.mime),now=new Date().toISOString();await db.from("project_attachment_links").update({attachment_mime_type:g.mime,attachment_size_bytes:g.size,content_sha256:hash,storage_backend:"supabase-storage",storage_bucket:BUCKET,storage_path:path,archived_at:now,archive_method:"gmail-storage-v1",analysis_status:"archived",updated_at:now}).eq("id",link.id);
  const x=await extract(g.b,link.attachment_name||"",g.mime);let a:any=null,bomResult={inserted:0,already:[] as any[],conflicts:[] as any[]},bs="none";
  if(x.text.trim()){
    a=analyzeText(x.text,{name:link.attachment_name||"",mime:g.mime});try{bomResult=await bom(project,link,a);}catch(e){a.apply_error=String(e);}
    const lowReview=(a.review_bom_candidates||[]).length,conflicts=bomResult.conflicts.length,embedded=Array.isArray(x.embedded_pending)?x.embedded_pending:[],embeddedNote=embedded.length?`\nArkivi ka gjithashtu elemente per review:\n${embedded.slice(0,8).join('\n')}`:'';
    if(conflicts){bs=bomResult.inserted?"partial_conflict_review":"conflict_review";const details=bomResult.conflicts.slice(0,5).map((c:any)=>`${c.source_locator}: dokumenti ${c.document_kg} kg, BOM ${c.existing_kg} kg (${c.difference_pct}%)`).join('\n');await task(project,link,`Dokumenti eshte i qarte, por bie ndesh me BOM-in ekzistues. Asnje vlere ekzistuese nuk u mbishkrua.\n${details}${embeddedNote}`,conflicts+lowReview+embedded.length);}
    else if(bomResult.inserted&&lowReview){bs="partial_review";await task(project,link,`Dokumenti ka edhe pozicione teknike qe nuk plotesojne pragun e sigurte per shkrim automatik ne BOM.${embeddedNote}`,lowReview+embedded.length);}
    else if(bomResult.inserted&&embedded.length){bs="partial_review";await task(project,link,`Pjesa e qarte u trajtua, por disa skedare brenda arkivit kerkojne review.${embeddedNote}`,embedded.length);}
    else if(bomResult.inserted)bs="applied";
    else if(bomResult.already.length&&lowReview){bs="review";await task(project,link,`Pozicionet e qarta ekzistojne tashme ne BOM, por dokumenti ka edhe pozicione qe kerkojne verifikim.${embeddedNote}`,lowReview+embedded.length);}
    else if(bomResult.already.length&&embedded.length){bs="review";await task(project,link,`Pozicionet e qarta ekzistojne ne BOM, por arkivi ka skedare qe kerkojne review.${embeddedNote}`,embedded.length);}
    else if(bomResult.already.length)bs="already_present";
    else if(lowReview){bs="review";await task(project,link,`Dokumenti ka pozicione teknike qe nuk plotesojne pragun e sigurte per shkrim automatik ne BOM.${embeddedNote}`,lowReview+embedded.length);}
    else if(embedded.length){bs="review";await task(project,link,`Arkivi u analizua pjeserisht; disa skedare kerkojne konvertim ose review.${embeddedNote}`,embedded.length);}
  }else if(["needs_conversion","needs_ocr","review","unsupported"].includes(x.status)){
    bs=x.status==="needs_conversion"?"needs_conversion":"review";await task(project,link,x.error||"Dokumenti u ruajt, por permbajtja nuk mund te nxirret me besueshmeri automatikisht.");
  }
  const status=a?"analyzed":x.status,{error:ue}=await db.from("project_attachment_links").update({analysis_status:status,analysis_method:x.method,extracted_text:a?.text||null,extracted_data:a?{facts:a.facts,file_name:link.attachment_name,mime_type:g.mime,bom_existing_matches:bomResult.already.length,bom_conflicts:bomResult.conflicts,embedded_entries:x.embedded_entries||[],embedded_pending:x.embedded_pending||[]}:{file_name:link.attachment_name,mime_type:g.mime,reason:x.error||null,embedded_entries:x.embedded_entries||[],embedded_pending:x.embedded_pending||[]},analysis_confidence:a?.confidence??null,analysis_error:x.error||a?.apply_error||null,analyzed_at:new Date().toISOString(),bom_status:bs,bom_candidates:a?.bom_candidates||[],bom_applied_count:bomResult.inserted,updated_at:new Date().toISOString()}).eq("id",link.id);if(ue)throw ue;
  return {id:link.id,project_id:link.project_id,name:link.attachment_name,mime:g.mime,size:g.size,archived:true,analysis_status:status,analysis_method:x.method,characters:a?.text?.length||0,bom_candidates:a?.bom_candidates?.length||0,bom_applied:bomResult.inserted,bom_existing_matches:bomResult.already.length,bom_conflicts:bomResult.conflicts.length,bom_status:bs,embedded_entries:(x.embedded_entries||[]).length,embedded_pending:(x.embedded_pending||[]).length};
}
async function recordError(id:number,e:any){await db.from("project_attachment_links").update({analysis_status:"retry",analysis_error:String(e).slice(0,2000),updated_at:new Date().toISOString()}).eq("id",id);}
async function run(limit=5,apply=true){const max=Math.min(10,Math.max(1,Math.floor(Number(limit)||5))),{data,error}=await db.from("project_attachment_links").select(cols).in("analysis_status",["pending","retry","archived"]).order("created_at",{ascending:true}).limit(max);if(error)throw error;const out=[];for(const row of (data||[]) as L[]){try{out.push(await process(row,apply));}catch(e){if(apply)await recordError(row.id,e);out.push({id:row.id,name:row.attachment_name,error:String(e)});}}return {candidates:(data||[]).length,processed:out.filter((x:any)=>!x.error).length,errors:out.filter((x:any)=>x.error).length,items:out};}
async function processId(id:number){if(!Number.isInteger(id)||id<=0)throw new Error("Invalid attachment link id");const {data,error}=await db.from("project_attachment_links").select(cols).eq("id",id).maybeSingle();if(error)throw error;if(!data)throw new Error("Attachment link not found");try{return await process(data as L,true);}catch(e){await recordError(id,e);throw e;}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!(await auth(req)))return new Response(JSON.stringify({ok:false,error:"unauthorized"}),{status:401,headers:{...cors,"Content-Type":"application/json"}});try{const u=new URL(req.url);let action=u.searchParams.get("action")||"run",p:any={};if(req.method==="POST")try{p=await req.json();action=p.action||action;}catch{}if(action==="ping")return new Response(JSON.stringify({ok:true,service:"project-document-intake-v8"}),{headers:{...cors,"Content-Type":"application/json"}});const limit=Number(u.searchParams.get("limit")||p.limit||5);if(action==="preview")return new Response(JSON.stringify({ok:true,...await run(limit,false)}),{headers:{...cors,"Content-Type":"application/json"}});if(action==="run")return new Response(JSON.stringify({ok:true,...await run(limit,true)}),{headers:{...cors,"Content-Type":"application/json"}});if(action==="process_id"){const id=Number(u.searchParams.get("id")||p.id||0);return new Response(JSON.stringify({ok:true,item:await processId(id)}),{headers:{...cors,"Content-Type":"application/json"}});}return new Response(JSON.stringify({ok:false,error:`unknown action: ${action}`}),{status:400,headers:{...cors,"Content-Type":"application/json"}});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:{...cors,"Content-Type":"application/json"}});}});
