import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const BUCKET='project-source-files';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, x-pppp-worker-id, x-pppp-worker-token','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const text=(v:unknown,max=1000)=>String(v==null?'':v).trim().slice(0,max);
const safeName=(v:string)=>text(v,240).replace(/[\\/\0\r\n]+/g,'_').replace(/\s+/g,' ').trim()||'document.bin';

async function sha256Hex(v:string|Uint8Array){const bytes=typeof v==='string'?new TextEncoder().encode(v):v;const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function authenticate(req:Request){const workerId=text(req.headers.get('x-pppp-worker-id'),120),raw=req.headers.get('x-pppp-worker-token')||'';if(!workerId||!raw)return null;const {data,error}=await db.from('local_ocr_workers').select('worker_id,token_sha256,enabled').eq('worker_id',workerId).maybeSingle();if(error||!data||data.enabled!==true)return null;const actual=await sha256Hex(raw),stored=String(data.token_sha256||'');if(!safeEqual(actual,stored)){const legacy=await sha256Hex(raw+'\n');if(!safeEqual(legacy,stored))return null;}await db.from('local_ocr_workers').update({last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('worker_id',workerId);return workerId;}
function archived(payload:any){return Array.isArray(payload?.archived_documents)?payload.archived_documents:[];}
function normalizeName(v:any){return text(v,500).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}

async function claim(workerId:string){const {data:rows,error}=await db.from('pppp_tender_fetch_queue').select('*').eq('auth_required',true).in('status',['queued','retry']).order('requested_at',{ascending:true}).limit(5);if(error)throw error;for(const row of rows||[]){const now=new Date().toISOString(),nextPayload={...(row.payload||{}),worker_id:workerId,claimed_at:now};const {data:claimed,error:e}=await db.from('pppp_tender_fetch_queue').update({status:'processing',last_attempt_at:now,attempt_count:Number(row.attempt_count||0)+1,last_error:null,payload:nextPayload,updated_at:now}).eq('tender_watch_id',row.tender_watch_id).in('status',['queued','retry']).select('*').maybeSingle();if(e)throw e;if(claimed)return{ok:true,job:jobPayload(claimed)};}return{ok:true,job:null};}
function jobPayload(row:any){return{tender_watch_id:String(row.tender_watch_id),source:String(row.source||'KRPP'),expected_documents:Array.isArray(row.protected_documents)?row.protected_documents:[],detail_url:text(row?.payload?.detail_url,2000)||null,procurement_no:text(row?.payload?.procurement_no,500)||null,title:text(row?.payload?.title,1000)||null,attempt_count:Number(row.attempt_count||0),archived_documents:archived(row.payload)};}
async function current(workerId:string){const {data,error}=await db.from('pppp_tender_fetch_queue').select('*').eq('status','processing').eq('payload->>worker_id',workerId).order('last_attempt_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return{ok:true,job:data?jobPayload(data):null};}
async function upload(workerId:string,req:Request){const form=await req.formData(),tenderId=text(form.get('tender_watch_id'),80),file=form.get('file');if(!tenderId||!(file instanceof File))return json({ok:false,error:'tender_watch_id and file are required'},400);if(file.size<=0||file.size>30*1024*1024)return json({ok:false,error:'file size must be 1..30MB'},413);const {data:row,error}=await db.from('pppp_tender_fetch_queue').select('*').eq('tender_watch_id',tenderId).maybeSingle();if(error)throw error;if(!row||row.status!=='processing'||String(row?.payload?.worker_id||'')!==workerId)return json({ok:false,error:'job is not owned by this worker'},409);const bytes=new Uint8Array(await file.arrayBuffer()),hash=await sha256Hex(bytes),name=safeName(text(form.get('filename'),240)||file.name),mime=text(file.type,160)||'application/octet-stream',path=`tender-protected/${tenderId}/${hash.slice(0,16)}-${name}`;const {error:upErr}=await db.storage.from(BUCKET).upload(path,bytes,{contentType:mime,upsert:true});if(upErr)throw upErr;const entry={name,mime_type:mime,bucket:BUCKET,path,sha256:hash,size_bytes:file.size,archived_at:new Date().toISOString(),worker_id:workerId};const existing=archived(row.payload).filter((x:any)=>String(x?.sha256||'')!==hash);const next=[...existing,entry];await db.from('pppp_tender_fetch_queue').update({payload:{...(row.payload||{}),archived_documents:next},updated_at:new Date().toISOString()}).eq('tender_watch_id',tenderId);return json({ok:true,tender_watch_id:tenderId,document:entry});}
async function complete(workerId:string,body:any){const tenderId=text(body?.tender_watch_id,80);if(!tenderId)return json({ok:false,error:'invalid tender_watch_id'},400);const {data:row,error}=await db.from('pppp_tender_fetch_queue').select('*').eq('tender_watch_id',tenderId).maybeSingle();if(error)throw error;if(!row||row.status!=='processing'||String(row?.payload?.worker_id||'')!==workerId)return json({ok:false,error:'job is not owned by this worker'},409);const docs=archived(row.payload),expected=Array.isArray(row.protected_documents)?row.protected_documents:[],got=new Set(docs.map((x:any)=>normalizeName(x?.name)));const missing=expected.filter((x:string)=>!got.has(normalizeName(x)));if(missing.length)return json({ok:false,error:'expected documents are still missing',missing},409);const now=new Date().toISOString(),queuePayload={...(row.payload||{}),completed_at:now,completed_by:workerId};const {data:tender,error:tErr}=await db.from('kek_tender_watch').select('payload').eq('id',tenderId).maybeSingle();if(tErr)throw tErr;const tenderPayload={...(tender?.payload||{}),protected_archive:docs,protected_archive_updated_at:now};await db.from('kek_tender_watch').update({payload:tenderPayload,updated_at:now}).eq('id',tenderId);await db.from('pppp_tender_fetch_queue').update({status:'ready',payload:queuePayload,last_error:null,updated_at:now}).eq('tender_watch_id',tenderId);return json({ok:true,tender_watch_id:tenderId,archived_documents:docs.length,status:'ready'});}
async function fail(workerId:string,body:any){const tenderId=text(body?.tender_watch_id,80),errText=text(body?.error||'Worker reported failure',1500);if(!tenderId)return json({ok:false,error:'invalid tender_watch_id'},400);const {data:row,error}=await db.from('pppp_tender_fetch_queue').select('status,attempt_count,payload').eq('tender_watch_id',tenderId).maybeSingle();if(error)throw error;if(!row||row.status!=='processing'||String(row?.payload?.worker_id||'')!==workerId)return json({ok:false,error:'job is not owned by this worker'},409);const status=Number(row.attempt_count||0)>=3?'failed':'retry';await db.from('pppp_tender_fetch_queue').update({status,last_error:errText,updated_at:new Date().toISOString()}).eq('tender_watch_id',tenderId);return json({ok:true,tender_watch_id:tenderId,status});}
async function heartbeat(workerId:string,body:any){const tenderId=text(body?.tender_watch_id,80);if(!tenderId)return json({ok:false,error:'invalid tender_watch_id'},400);const {data,error}=await db.from('pppp_tender_fetch_queue').update({updated_at:new Date().toISOString()}).eq('tender_watch_id',tenderId).eq('status','processing').eq('payload->>worker_id',workerId).select('tender_watch_id').maybeSingle();if(error)throw error;return json({ok:!!data,tender_watch_id:tenderId},data?200:409);}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const workerId=await authenticate(req);if(!workerId)return json({ok:false,error:'unauthorized'},401);try{const url=new URL(req.url);if(req.method==='POST'&&String(req.headers.get('content-type')||'').includes('multipart/form-data'))return await upload(workerId,req);let body:any={};if(req.method==='POST'){try{body=await req.json();}catch{body={};}}const action=String(body?.action||url.searchParams.get('action')||'ping');if(action==='ping')return json({ok:true,service:'pppp-tender-fetch-worker-v1',worker_id:workerId});if(action==='claim')return json(await claim(workerId));if(action==='current')return json(await current(workerId));if(action==='complete')return await complete(workerId,body);if(action==='fail')return await fail(workerId,body);if(action==='heartbeat')return await heartbeat(workerId,body);return json({ok:false,error:`unknown action: ${action}`},400);}catch(e){return json({ok:false,error:String(e).slice(0,1500)},500);}});
