const txt=(v,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);
const norm=v=>txt(v,2000).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const first=(...xs)=>xs.map(x=>txt(x,2000)).find(Boolean)||'';
const esc=v=>txt(v,12000).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const emailDomain=v=>{const e=txt(v,320).toLowerCase(),i=e.lastIndexOf('@');return i>0?e.slice(i+1):'';};

export const COPY_POLICY_VERSION='pppp-commercial-copy-policy-v4';
export const PRISTEEL_LOGO_URL='https://ci3.googleusercontent.com/mail-sig/AIorK4zBbQr6xZC9wHaoIhmL0bKLl8uPOlacg1Q4uZvshbApeKuRiHczkMprJts9P2a3CvsPovpqy2N5ZRba';
const SIGNATURE=['Arianit Vllahiu','Head of Business Development','+383 (0) 44 244 699','arianit.vllahiu@prissteel.com','www.prissteel.com'].join('\n');
const SIGNATURE_HTML=`<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:16px;border-collapse:collapse;font-family:Arial,sans-serif;color:#1f2937"><tbody><tr><td valign="middle" style="padding:0 18px 0 0"><img src="${PRISTEEL_LOGO_URL}" width="182" alt="PRISTEEL" style="display:block;border:0;outline:none;text-decoration:none;width:182px;height:auto"></td><td valign="middle" style="border-left:2px solid #1a73e8;padding:0 0 0 18px"><div style="font-size:17px;line-height:1.25;font-weight:700;color:#1f2937">Arianit Vllahiu</div><div style="font-size:15px;line-height:1.35;color:#1f2937">Head of Business Development</div><div style="margin-top:8px;font-size:14px;line-height:1.5"><a href="tel:+38344244699" style="color:#1a73e8;text-decoration:underline">+383 (0) 44 244 699</a></div><div style="font-size:14px;line-height:1.5"><a href="mailto:arianit.vllahiu@prissteel.com" style="color:#1a73e8;text-decoration:underline">arianit.vllahiu@prissteel.com</a></div><div style="font-size:14px;line-height:1.5"><a href="https://www.prissteel.com" style="color:#1a73e8;text-decoration:underline">www.prissteel.com</a></div></td></tr></tbody></table>`;

const DACH=new Set(['de','deu','ger','germany','deutschland','at','aut','austria','osterreich','oesterreich','ch','che','switzerland','schweiz','li','lie','liechtenstein']);
const BCS=new Set(['hr','hrv','croatia','hrvatska','rs','srb','serbia','srbija','me','mne','montenegro','crna gora']);
const INTERNAL=/(?:\bunknown\b|company\s*profile|unternehmensprofil|outreach|readiness|draft\s*(?:only|vetem)|human\s*approval|internal|workflow|personalization|company\s*fit|\bscore\b|pergatit\s+draft|mos\s+e\s+dergo|do\s+not\s+send|prepare\s+(?:an?\s+)?draft)/i;

function decode(v){return txt(v,5000).replace(/&amp;quot;/gi,'"').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');}
function tokenLanguage(v){const s=norm(v).replace(/[^a-z0-9 ]+/g,' ').trim();for(const x of DACH)if(s===x||s.startsWith(x+' ')||s.endsWith(' '+x)||s.includes(' '+x+' '))return'de';for(const x of BCS)if(s===x||s.startsWith(x+' ')||s.endsWith(' '+x)||s.includes(' '+x+' '))return'bcs';return'';}
export function resolveDraftLanguage(action={},tender={},recipient={}){const title=decode(first(action?.tender_title,tender?.title,action?.payload?.project_title)),prefix=(title.split(/\s+[–—]\s+/)[0]||'').trim(),winner=tender?.winner||{},values=[prefix,recipient?.country,recipient?.country_code,action?.country,action?.market,winner?.country,...(Array.isArray(winner?.countries)?winner.countries:[]),...(Array.isArray(tender?.place_of_performance)?tender.place_of_performance:[])];for(const v of values){const x=tokenLanguage(v);if(x)return x;}const d=emailDomain(recipient?.email||action?.target_email);if(/\.(de|at|ch|li)$/.test(d))return'de';if(/\.(hr|rs|me)$/.test(d))return'bcs';return'en';}

export function tedReference(tender={}){return first(tender?.publication_no,tender?.procurement_no,tender?.ted_reference,tender?.notice_id,tender?.payload?.publication_no,tender?.payload?.procurement_no).replace(/^TED[-\s:]*/i,'').trim();}
export function tedUrl(tender={}){return first(tender?.source_url,tender?.detail_url,tender?.payload?.source_url,tender?.payload?.detail_url);}
function normalizeReference(v){return txt(v,80).replace(/(?<=\d)O(?=\b)/g,'0').replace(/(?<=\d)o(?=\b)/g,'0');}
function titleWithoutSource(v,ref=''){let s=decode(v);if(ref)s=s.split(ref).join(' ');s=s.replace(/\bTED\b(?:\s*[-:#]?\s*\d{5,}-\d{4})?/gi,' ').replace(/\s+/g,' ').replace(/^[\s|:;,.\-–—]+|[\s|:;,.\-–—]+$/g,'').trim();const parts=s.split(/\s+[–—]\s+/).map(x=>x.trim()).filter(Boolean);if(parts.length>=3&&tokenLanguage(parts[0]))return parts.slice(2).join(' – ');if(parts.length>=2&&tokenLanguage(parts[0]))return parts.slice(1).join(' – ');return s;}
function visibleReference(title,tender){const source=first(title,tender?.payload?.ted_details?.procedure_title,tender?.payload?.ted_details?.lot_titles?.[0]),m=source.match(/\b(?:VOB\s*)?\d{1,3}-[0-9O]{2,4}\b|\bCL\s*V[_\s-]*\d+(?:[\/_-]\d+)*\b|\b[A-Z]{1,6}[_-]\d{2,}(?:[\/_-]\d+)*\b/i);return normalizeReference(m?.[0]||'');}
function shortText(v,max=160){const s=decode(v).replace(/[\r\n\t]+/g,' ').replace(/\s+/g,' ').trim();if(!s||s.length>max||INTERNAL.test(s)||/(?:^|\s)[-•]\s+.+(?:\s[-•]\s+.+){1,}/.test(s))return'';return s;}
function projectContext(action,tender,language){const rawTitle=first(action?.tender_title,tender?.title,action?.payload?.project_title),all=decode([rawTitle,tender?.payload?.description,tender?.payload?.short_description,tender?.payload?.ted_details?.procedure_description].filter(Boolean).join(' ')),ref=visibleReference(rawTitle,tender),clean=titleWithoutSource(rawTitle,ref),location=/\bstralsund\b/i.test(all)?'Stralsund':'',trio=['Athalassa','Anatoliko','FIZ'].filter(x=>new RegExp('\\b'+x+'\\b','i').test(all)),battery=/battery|batteriespeicher|storage energy/i.test(all);let anchor=ref||(trio.length>=2?trio.join(' / '):clean.replace(/^.*?\b(?:Welding|Structural steelworks|Steel material)\s+[–—]\s+/i,''));anchor=shortText(anchor,72)||'Steel project';let fact='';if(language==='de'&&ref&&location&&/stahlbau|schlosser/i.test(all))fact=`Projekt ${ref} in ${location} · Stahlbau-/Schlosserumfang`;else if(language==='en'&&trio.length>=2)fact=`${trio.join(', ')}${trio.length>2?' battery storage projects':' projects'}`;else if(language==='bcs')fact=`Projekat ${anchor}`;else if(language==='de')fact=`Projekt ${anchor}`;else fact=`Project ${anchor}`;return{anchor,reference:ref,location,scope:/stahlbau|schlosser/i.test(all)?'steelwork/metalwork':battery?'battery-storage steel scope':'steel scope',public_fact:shortText(fact,160)};}

function companyRole(action,tender){const route=txt(action?.route,80).toUpperCase(),raw=norm(first(action?.company_role,action?.payload?.company_type,tender?.winner?.company_type,tender?.winner?.company_classification?.company_type));if(route==='TED_PRODUCER'||/producer|fabricator|manufacturer|oem/.test(raw))return'steel_fabricator';if(route==='DIRECT_RAW_MATERIAL'||/material.?buyer|steel.?consumer/.test(raw))return'material_buyer';if(route==='TED_CONSORTIUM'||/consortium/.test(raw))return'consortium_member';if(route==='TED_GC'||/gc|epc|contractor/.test(raw))return'gc_epc';if(/trader|distributor/.test(raw))return'trader_distributor';if(/industrial/.test(raw))return'industrial_manufacturer';return'unknown';}
const GENERIC_LOCAL=new Set(['info','office','contact','kontakt','mail','hello','post','admin','sekretariat','service']);
function recipientRole(recipient={}){const email=txt(recipient?.email,320).toLowerCase(),local=(email.split('@')[0]||'').replace(/\+.*/,''),name=txt(recipient?.name,180),role=norm(first(recipient?.functional_role,recipient?.job_title,recipient?.role,recipient?.purpose));if(GENERIC_LOCAL.has(local))return'generic_inbox';if(/procurement|purchas|einkauf|sourcing|beschaffung|tender|vergabe|stahl|material/.test(role+' '+local))return name?'named_procurement':'functional_procurement';if(/project|projekt|technical|technik|engineer|engineering|konstruk/.test(role))return'named_project_technical';return name?'named_general':'generic_inbox';}
function explicitGermanGender(recipient,name){const raw=norm(first(recipient?.salutation,recipient?.honorific,recipient?.address_title,recipient?.title_prefix,recipient?.gender)),from=norm(name);if(/^(herr|mr|mister|male|mann|m|masculine)(\b|$)/.test(raw)||/^(herr|mr\.?|mister)\s+/.test(from))return'male';if(/^(frau|mrs|ms|miss|female|weiblich|w|f|feminine)(\b|$)/.test(raw)||/^(frau|mrs\.?|ms\.?|miss)\s+/.test(from))return'female';return'';}
function surname(name){let s=txt(name,180).replace(/^(?:(?:herr|frau|mr\.?|mrs\.?|ms\.?|miss|prof\.?|dr\.?)\s+)+/i,'').trim(),p=s.split(/\s+/).filter(Boolean);return p[p.length-1]||'';}
function greeting(language,recipient){const rr=recipientRole(recipient),name=rr==='generic_inbox'||rr==='functional_procurement'?'':txt(recipient?.name,180);if(language==='de'){const g=explicitGermanGender(recipient,name),sn=surname(name);return g==='male'&&sn?'Sehr geehrter Herr '+sn+',':g==='female'&&sn?'Sehr geehrte Frau '+sn+',':'Sehr geehrte Damen und Herren,';}if(language==='bcs')return name?'Poštovani '+name+',':'Poštovani,';return name?'Dear '+name+',':'Hello,';}
function closing(language){return language==='de'?'Mit freundlichen Grüßen':language==='bcs'?'S poštovanjem':'Kind regards';}
function resolveOfferModel(action,role){const motion=txt(action?.outreach_motion,80),route=txt(action?.route,80).toUpperCase(),stored=txt(action?.pristeel_offer_model,80),timing=txt(action?.timing_classification,80);if(motion==='future_supplier_qualification'||timing==='future_supplier_qualification'||stored==='future_supplier_qualification')return'future_supplier_qualification';if(route==='DIRECT_RAW_MATERIAL'||motion==='material_buyer'||stored==='material_supply'||role==='material_buyer')return'material_supply';if(role==='steel_fabricator'||route==='TED_PRODUCER'||motion==='external_production_capacity'||stored==='external_production_capacity')return'external_production_capacity';return'fabricated_steel_package';}
function intro(language,ctx){if(language==='de'){if(ctx.reference&&ctx.location&&ctx.scope==='steelwork/metalwork')return`ich melde mich bezüglich des Projekts ${ctx.reference} in ${ctx.location} und des dort vorgesehenen Stahlbau-/Schlosserumfangs.`;return`ich melde mich bezüglich des Projekts ${ctx.anchor}.`;}if(language==='bcs')return`javljam Vam se u vezi sa projektom ${ctx.anchor}.`;if(ctx.public_fact&&/Athalassa/i.test(ctx.public_fact))return`I am contacting you regarding the ${ctx.public_fact}.`;return`I am contacting you regarding ${ctx.anchor}.`;}
function credibility(language,material=false){if(language==='de')return`PRISTEEL verbindet erfahrenes Stahlindustrie-Management mit einem etablierten ${material?'Beschaffungs- und Fertigungsnetzwerk':'Fertigungsnetzwerk'} in Südosteuropa. Wo vertraglich erforderlich, kann die Leistung über Bankgarantien der ProCredit Bank abgesichert werden.`;if(language==='bcs')return`PRISTEEL kombinuje iskusno upravljanje u industriji čelika sa etabliranom ${material?'mrežom dobavljača i proizvodnih partnera':'mrežom proizvodnih partnera'} u Jugoistočnoj Evropi. Kada je potrebno, ugovorno izvršenje može biti podržano bankarskim garancijama preko ProCredit Bank.`;return`PRISTEEL combines experienced steel-industry management with an established ${material?'steel supply and fabrication':'fabrication'} network in Southeast Europe. Where required, contractual performance can be supported by bank guarantees through ProCredit Bank.`;}
function offerCopy(language,model,ctx,recipient){const p=intro(language,ctx),c=credibility(language,model==='material_supply'),a=ctx.anchor,rr=recipientRole(recipient),referral=rr==='generic_inbox'?(language==='de'?'Falls eine andere Person dafür zuständig ist, freue ich mich über einen kurzen Hinweis auf den richtigen Kontakt.':language==='bcs'?'Ako je za ovaj opseg zadužena druga osoba, bio bih zahvalan na kontaktu.':'If another colleague is responsible for this scope, I would appreciate a referral.'):'';
 if(model==='external_production_capacity'){
  if(language==='de')return{subject:`${a} – externe Fertigungskapazität | PRISTEEL`,paras:[p,'Wenn Sie für klar definierte Pakete externe Fertigungskapazität einsetzen, kann PRISTEEL die technische Klärung, Build-to-Print-Fertigung, Oberflächenschutz, Qualitätsdokumentation und koordinierte DAP-Lieferung über einen Ansprechpartner übernehmen.','Ihr Team behält die Kontrolle über Projekt und Produktionsprioritäten; wir übernehmen die Abwicklung des ausgelagerten Pakets bis zur Lieferung.',c,'Nutzen Sie bei Kapazitätsspitzen externe Fertigung für klar abgegrenzte Pakete?',referral]};
  if(language==='bcs')return{subject:`${a} – vanjski proizvodni kapacitet | PRISTEEL`,paras:[p,'Ako koristite vanjski proizvodni kapacitet za jasno definisane pakete, PRISTEEL može koordinirati tehničko usaglašavanje, build-to-print proizvodnju, površinsku zaštitu, dokumentaciju kvaliteta i DAP isporuku.','Vaš tim zadržava kontrolu nad projektom i proizvodnim prioritetima; mi vodimo izdvojeni paket do isporuke.',c,'Koristite li vanjsku proizvodnju za jasno odvojene pakete u periodima većeg opterećenja?',referral]};
  return{subject:`${a} – external fabrication capacity | PRISTEEL`,paras:[p,'If you use external fabrication capacity for defined packages, PRISTEEL can coordinate technical clarification, build-to-print fabrication, surface treatment, quality documentation and DAP delivery through one point of contact.','Your team keeps control of the project and production priorities; we manage the outsourced package through delivery.',c,'Do you use external fabrication for clearly defined packages when internal capacity is constrained?',referral]};
 }
 if(model==='material_supply'){
  if(language==='de')return{subject:`${a} – Stahlmaterial | PRISTEEL`,paras:[p,'PRISTEEL koordiniert projektbezogene Stahlmaterialpakete aus qualifizierten Bezugsquellen – Profile, Bleche sowie Rohre/Hohlprofile mit Dokumentation nach EN 10204 3.1, optionaler Bearbeitung und DAP-Lieferung über einen Ansprechpartner.',c,'Wenn Sie diese Materialkategorie einkaufen, senden Sie uns gerne eine aktuelle RFQ oder Materialliste mit Lieferort.',referral]};
  if(language==='bcs')return{subject:`${a} – čelični materijal | PRISTEEL`,paras:[p,'PRISTEEL koordinira projektne pakete čeličnog materijala iz kvalifikovanih izvora – profile, limove i cijevi/šuplje profile sa EN 10204 3.1 dokumentacijom, opcionom obradom i DAP isporukom preko jedne kontakt tačke.',c,'Ako nabavljate ovu kategoriju materijala, pošaljite nam aktuelni RFQ ili listu materijala i mjesto isporuke.',referral]};
  return{subject:`${a} – steel material | PRISTEEL`,paras:[p,'PRISTEEL coordinates project-specific steel material from qualified sources — sections, plates and tubes/hollow sections with EN 10204 3.1 documentation, optional processing and DAP delivery through one commercial contact.',c,'If you purchase this material category, send us one current RFQ or material list and the delivery point.',referral]};
 }
 if(model==='future_supplier_qualification'){
  if(language==='de')return{subject:`${a} – Lieferantenqualifizierung Stahl | PRISTEEL`,paras:['ich melde mich im Hinblick auf künftige Stahlpakete.','PRISTEEL kann für klar definierte Umfänge Materialbeschaffung, Build-to-Print-Fertigung, Oberflächenschutz, Qualitätsdokumentation und DAP-Lieferung über einen technischen und kaufmännischen Ansprechpartner koordinieren.',c,'Wer ist bei Ihnen für die Qualifizierung künftiger Partner für Stahlpakete zuständig?',referral]};
  if(language==='bcs')return{subject:`${a} – kvalifikacija dobavljača čelika | PRISTEEL`,paras:['javljam Vam se u vezi sa budućim čeličnim paketima.','PRISTEEL može za jasno definisane opsege koordinirati nabavku materijala, build-to-print proizvodnju, površinsku zaštitu, dokumentaciju kvaliteta i DAP isporuku preko jedne tehničke i komercijalne kontakt tačke.',c,'Ko je kod Vas zadužen za kvalifikaciju budućih partnera za čelične pakete?',referral]};
  return{subject:`${a} – future steel partner qualification | PRISTEEL`,paras:['I am contacting you regarding future steel packages.','For clearly defined scopes, PRISTEEL can coordinate material sourcing, build-to-print fabrication, surface treatment, quality documentation and DAP delivery through one technical and commercial point of contact.',c,'Who handles qualification of future partners for steel packages?',referral]};
 }
 if(language==='de')return{subject:`${a} – Stahlpaket | PRISTEEL`,paras:[p,'PRISTEEL kann für ein klar abgegrenztes Stahlpaket die technische und kaufmännische Abwicklung aus einer Hand übernehmen – von Materialbeschaffung und Build-to-Print-Fertigung über Oberflächenschutz und Qualitätsdokumentation bis zur koordinierten DAP-Lieferung.','Die Projektsteuerung bleibt bei Ihnen; wir übernehmen die Abwicklung des vereinbarten Stahlpakets von Zeichnung bzw. Stückliste bis zur Lieferung.',c,'Falls noch ein klar abgegrenztes Stahlbau- oder Fertigungspaket extern vergeben werden soll, senden Sie uns gerne Zeichnungen oder Stückliste – wir übernehmen die weitere Abwicklung.',referral]};
 if(language==='bcs')return{subject:`${a} – čelični paket | PRISTEEL`,paras:[p,'PRISTEEL može preuzeti tehničku i komercijalnu realizaciju jasno definisanog čeličnog paketa – od nabavke materijala i build-to-print proizvodnje do površinske zaštite, dokumentacije kvaliteta i koordinirane DAP isporuke.','Upravljanje projektom ostaje kod Vas; mi vodimo ugovoreni čelični paket od nacrta ili liste materijala do isporuke.',c,'Ako postoji jasno odvojen čelični ili proizvodni paket za vanjskog partnera, pošaljite nam nacrte ili listu materijala – mi preuzimamo dalje.',referral]};
 return{subject:`${a} – steel package | PRISTEEL`,paras:[p,'PRISTEEL can take full responsibility for a clearly defined steel package — from material sourcing and build-to-print fabrication to surface treatment, quality documentation and coordinated DAP delivery — with one technical and commercial point of contact.','You remain in control of the project. We take ownership of the steel package from drawings or BOM through delivery.',c,'If there is a structural or fabricated steel package you would prefer to place with one external partner, send us the drawings or BOM and we will take it from there.',referral]};
}
function htmlParagraph(v){return v?`<p style="margin:0 0 14px 0">${esc(v)}</p>`:'';}
export function buildTedDraftContent(action={},tender={},recipient={}){const language=resolveDraftLanguage(action,tender,recipient),role=companyRole(action,tender),ctx=projectContext(action,tender,language),offerModel=resolveOfferModel(action,role),copy=offerCopy(language,offerModel,ctx,recipient),hello=greeting(language,recipient),close=closing(language),paras=copy.paras.filter(Boolean),plainBody=[hello,...paras,close,SIGNATURE].join('\n\n'),htmlBody='<div dir="ltr" style="font-family:Arial,sans-serif;font-size:14px;line-height:1.5;color:#202124">'+htmlParagraph(hello)+paras.map(htmlParagraph).join('')+`<p style="margin:0">${esc(close)}</p>`+SIGNATURE_HTML+'</div>';return{subject:copy.subject,plain_body:plainBody,html_body:htmlBody,offer_model:offerModel,company_role:role,recipient_role:recipientRole(recipient),selected_public_facts:[ctx.public_fact].filter(Boolean),copy_policy_version:COPY_POLICY_VERSION,language,body:plainBody,recipient_kind:recipientRole(recipient)==='generic_inbox'?'general':'direct',tender_reference:tedReference(tender)||null,tender_url:tedUrl(tender)||null,signature:SIGNATURE,signature_html:SIGNATURE_HTML};}
export const PRISTEEL_SIGNATURE=SIGNATURE;
export const PRISTEEL_SIGNATURE_HTML=SIGNATURE_HTML;
