const txt=(v,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);
const norm=v=>txt(v,2000).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const first=(...xs)=>xs.map(x=>txt(x,2000)).find(Boolean)||'';
const esc=v=>txt(v,12000).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const emailDomain=v=>{const e=txt(v,320).toLowerCase(),i=e.lastIndexOf('@');return i>0?e.slice(i+1):'';};

export const COPY_POLICY_VERSION='pppp-commercial-copy-policy-v5';
export const PRISTEEL_LOGO_URL='https://ci3.googleusercontent.com/mail-sig/AIorK4zBbQr6xZC9wHaoIhmL0bKLl8uPOlacg1Q4uZvshbApeKuRiHczkMprJts9P2a3CvsPovpqy2N5ZRba';
const SIGNATURE=['Arianit Vllahiu','Head of Business Development','+383 (0) 44 244 699','arianit.vllahiu@prissteel.com','www.prissteel.com'].join('\n');
const SIGNATURE_HTML=`<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:16px;border-collapse:collapse;font-family:Arial,sans-serif;color:#1f2937"><tbody><tr><td valign="middle" style="padding:0 18px 0 0"><img src="${PRISTEEL_LOGO_URL}" width="182" alt="PRISTEEL" style="display:block;border:0;outline:none;text-decoration:none;width:182px;height:auto"></td><td valign="middle" style="border-left:2px solid #2e7d32;padding:0 0 0 18px"><div style="font-size:17px;line-height:1.25;font-weight:700;color:#1f2937">Arianit Vllahiu</div><div style="font-size:15px;line-height:1.35;color:#1f2937">Head of Business Development</div><div style="margin-top:8px;font-size:14px;line-height:1.5"><a href="tel:+38344244699" style="color:#1a73e8;text-decoration:underline">+383 (0) 44 244 699</a></div><div style="font-size:14px;line-height:1.5"><a href="mailto:arianit.vllahiu@prissteel.com" style="color:#1a73e8;text-decoration:underline">arianit.vllahiu@prissteel.com</a></div><div style="font-size:14px;line-height:1.5"><a href="https://www.prissteel.com" style="color:#1a73e8;text-decoration:underline">www.prissteel.com</a></div></td></tr></tbody></table>`;

const DACH=new Set(['de','deu','ger','germany','deutschland','at','aut','austria','osterreich','oesterreich','ch','che','switzerland','schweiz','li','lie','liechtenstein']);
const BCS=new Set(['hr','hrv','croatia','hrvatska','rs','srb','serbia','srbija','me','mne','montenegro','crna gora']);
const INTERNAL=/(?:\bunknown\b|company\s*profile|unternehmensprofil|outreach|readiness|draft\s*(?:only|vetem)|human\s*approval|internal|workflow|personalization|company\s*fit|\bscore\b|pergatit\s+draft|mos\s+e\s+dergo|do\s+not\s+send|prepare\s+(?:an?\s+)?draft)/i;

function decode(v){return txt(v,5000).replace(/&amp;quot;/gi,'"').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');}
function tokenLanguage(v){const s=norm(v).replace(/[^a-z0-9 ]+/g,' ').trim();for(const x of DACH)if(s===x||s.startsWith(x+' ')||s.endsWith(' '+x)||s.includes(' '+x+' '))return'de';for(const x of BCS)if(s===x||s.startsWith(x+' ')||s.endsWith(' '+x)||s.includes(' '+x+' '))return'bcs';return'';}
export function resolveDraftLanguage(action={},tender={},recipient={}){const title=decode(first(action?.tender_title,tender?.title,action?.payload?.project_title)),prefix=(title.split(/\s+[–—]\s+/)[0]||'').trim(),winner=tender?.winner||{},values=[prefix,recipient?.country,recipient?.country_code,action?.country,action?.market,winner?.country,...(Array.isArray(winner?.countries)?winner.countries:[]),...(Array.isArray(tender?.place_of_performance)?tender.place_of_performance:[])];for(const v of values){const x=tokenLanguage(v);if(x)return x;}const d=emailDomain(recipient?.email||action?.target_email);if(/\.(de|at|ch|li)$/.test(d))return'de';if(/\.(hr|rs|me)$/.test(d))return'bcs';return'en';}

export function tedReference(tender={}){return first(tender?.publication_no,tender?.procurement_no,tender?.ted_reference,tender?.notice_id,tender?.payload?.publication_no,tender?.payload?.procurement_no).replace(/^TED[-\s:]*/i,'').trim();}
export function tedUrl(tender={}){return first(tender?.source_url,tender?.detail_url,tender?.payload?.source_url,tender?.payload?.detail_url);}
function normalizeReference(v){return txt(v,80).replace(/(?<=\d)O(?=\b)/g,'0').replace(/(?<=\d)o(?=\b)/g,'0');}
function titleWithoutSource(v,ref=''){let s=decode(v);if(ref)s=s.split(ref).join(' ');s=s.replace(/\bTED\b(?:\s*[-:#]?\s*\d{5,}-\d{4})?/gi,' ').replace(/\s+/g,' ').replace(/^[\s|:;,.\-–—]+|[\s|:;,.\-–—]+$/g,'').trim();const parts=s.split(/\s+[–—]\s+/).map(x=>x.trim()).filter(Boolean);if(parts.length>=3&&tokenLanguage(parts[0]))return parts.slice(2).join(' – ');if(parts.length>=2&&tokenLanguage(parts[0]))return parts.slice(1).join(' – ');return s;}
function visibleReference(title,tender){const source=first(title,tender?.payload?.ted_details?.procedure_title,tender?.payload?.ted_details?.lot_titles?.[0]),m=source.match(/\b(?:VOB\s*)?\d{1,3}-[0-9O]{2,4}\b|\bCL\s*V[_\s-]*\d+(?:[\/_-]\d+)*\b|\b[A-Z]{1,6}[_-]\d{2,}(?:[\/_-]\d+)*\b/i);return normalizeReference(m?.[0]||'');}
function shortText(v,max=160){const s=decode(v).replace(/[\r\n\t]+/g,' ').replace(/\s+/g,' ').trim();if(!s||s.length>max||INTERNAL.test(s)||/(?:^|\s)[-•]\s+.+(?:\s[-•]\s+.+){1,}/.test(s))return'';return s;}
function projectContext(action,tender,language){
 const rawTitle=first(action?.tender_title,tender?.title,action?.payload?.project_title),readiness=action?.payload?.outreach_readiness_v1||{},scopeText=first(readiness?.scope_evidence,action?.pristeel_scope,tender?.payload?.description,tender?.payload?.short_description),all=decode([rawTitle,scopeText,tender?.payload?.ted_details?.procedure_description].filter(Boolean).join(' ')),ref=visibleReference(rawTitle,tender),clean=titleWithoutSource(rawTitle,ref),location=/\bstralsund\b/i.test(all)?'Stralsund':'',trio=['Athalassa','Anatoliko','FIZ'].filter(x=>new RegExp('\\b'+x+'\\b','i').test(all)),battery=/battery|batteriespeicher|storage energy/i.test(all),pkg=normalizeReference(all.match(/\bVE\s*\d{1,3}-[0-9O]{2,5}\b/i)?.[0]||''),unit=all.match(/\bHaus\s+[IVXLC\d]+\b/i)?.[0]||'';
 const doors=/innent[uü]ren?\s+metall|metall(?:ische)?\s+innent[uü]ren?/i.test(all),structural=/stahlbau|schlosser/i.test(all),packageKind=doors?'metal_doors':structural?'structural_metalwork':battery?'battery_storage':'general_steel',scopeLabel=doors?(language==='de'?'Metall-Innentüren':'metal interior doors'):structural?(language==='de'?'Stahlbau-/Schlosserarbeiten':'structural steel/metalwork'):battery?'battery-storage steel scope':'';
 const components=[];if(doors)components.push(language==='de'?'Metall-Innentüren':'metal interior doors');if(/abbruch[^.\n]{0,80}stahlblecht[uü]ren/i.test(all))components.push(language==='de'?'Rückbau bestehender Stahlblechtüren':'removal of existing sheet-steel doors');if(/gel[aä]nder/i.test(all))components.push(language==='de'?'Geländer':'railings');if(/handl[aä]ufe?/i.test(all))components.push(language==='de'?'Handläufe':'handrails');if(/unterkonstruktion[^.\n]{0,80}lernbalkon/i.test(all))components.push(language==='de'?'Unterkonstruktionen der Lernbalkone':'learning-balcony substructures');
 const materialFacts=(Array.isArray(action?.personalization_facts)?action.personalization_facts:[]).map(x=>shortText(x,120)).filter(x=>x&&/\b(?:S\d{3}(?:JR|J0|J2)?|EN\s*\d{3,5}|HEA|HEB|IPE|RHS|SHS|CHS)\b/i.test(x)).slice(0,4),valueFact=(Array.isArray(action?.personalization_facts)?action.personalization_facts:[]).map(x=>shortText(x,80)).find(x=>/\b[\d.,]+\s*(?:EUR|GBP|CHF|USD)\b/i.test(x))||'';
 const tedRef=tedReference(tender);let anchor=[ref||(tedRef?[tedRef,clean].filter(Boolean).join(' · '):''),pkg].filter(Boolean).join(' · ')||(trio.length>=2?trio.join(' / '):clean.replace(/^.*?\b(?:Welding|Structural steelworks|Steel material)\s+[–—]\s+/i,''));anchor=shortText(anchor,88)||tedRef||'Steel project';const packageTitle=[unit,scopeLabel].filter(Boolean).join(' – '),subjectTitle=titleWithoutSource(clean,tedRef),subjectName=shortText(subjectTitle,88)||shortText(subjectTitle.slice(0,85).replace(/\s+\S*$/,''),88)||(language==='de'?'Projekt':language==='bcs'?'Projekt':'Project'),subjectBase=ref||pkg?anchor:trio.length>=2?trio.join(' / '):subjectName,subjectAnchor=packageTitle?`${subjectBase} – ${packageTitle}`:subjectBase;
 const projectGroup=trio.length>=2?`${trio.join(', ')}${trio.length>2?' battery storage projects':' projects'}`:'',verifiedFacts=[projectGroup,ref&&`Project ${ref}`,pkg&&`Package ${pkg}`,unit,scopeLabel,...components,valueFact].filter(Boolean),missingFacts=[];if(!materialFacts.length)missingFacts.push(language==='de'?'Materialgüten und Normen':'material grades and standards');if(!/\b(?:menge|quantity|tonnage|tonnen|st[uü]ck)\b/i.test(all))missingFacts.push(language==='de'?'Mengen/BOQ':'quantities/BOQ');if(!/zeichnung|drawing|planunterlagen/i.test(all))missingFacts.push(language==='de'?'Zeichnungen':'drawings');
 return{project_name:shortText([tedRef,titleWithoutSource(rawTitle)].filter(Boolean).join(' · '),500)||anchor,anchor,subject_anchor:subjectAnchor,reference:ref,package_code:pkg,unit,location,scope:structural?'steelwork/metalwork':battery?'battery-storage steel scope':'steel scope',scope_label:scopeLabel,package_kind:packageKind,components:[...new Set(components)],materials:[...new Set(materialFacts)],value:valueFact,verified_facts:[...new Set(verifiedFacts)].slice(0,8),missing_facts:[...new Set(missingFacts)],package_complete:!!(pkg&&scopeLabel&&materialFacts.length),public_fact:shortText(projectGroup||[ref&&`Project ${ref}`,pkg&&`package ${pkg}`,packageTitle].filter(Boolean).join(' · '),160)};
}

function companyRole(action,tender){const raw=norm(first(action?.company_role,action?.payload?.company_type,tender?.winner?.company_type,tender?.winner?.company_classification?.company_type));if(/trader[ _-]?consortium/.test(raw))return'gc_epc';const v2=norm(first(tender?.winner_role_v2?.category,tender?.winner?.role_v2?.category,action?.payload?.company_role_v2,action?.payload?.company_role_v2_detail?.category)),allowed=new Set(['steel_fabricator','gc_epc','trader_distributor','steel_mill_producer','consortium_jv','specialist_contractor','other_unclear']);if(allowed.has(v2))return v2;const route=txt(action?.route,80).toUpperCase();if(route==='TED_PRODUCER'||/producer|fabricator|manufacturer|oem/.test(raw))return'steel_fabricator';if(route==='DIRECT_RAW_MATERIAL'||/material.?buyer|steel.?consumer/.test(raw))return'material_buyer';if(route==='TED_CONSORTIUM'||/consortium/.test(raw))return'consortium_jv';if(route==='TED_GC'||/gc|epc|contractor/.test(raw))return'gc_epc';if(/trader|distributor/.test(raw))return'trader_distributor';if(/industrial/.test(raw))return'industrial_manufacturer';return'unknown';}
const GENERIC_LOCAL=new Set(['info','office','contact','kontakt','mail','hello','post','admin','sekretariat','service']);
function recipientRole(recipient={}){const email=txt(recipient?.email,320).toLowerCase(),local=(email.split('@')[0]||'').replace(/\+.*/,''),name=txt(recipient?.name,180),role=norm(first(recipient?.functional_role,recipient?.job_title,recipient?.role,recipient?.purpose));if(GENERIC_LOCAL.has(local))return'generic_inbox';if(/procurement|purchas|einkauf|sourcing|beschaffung|tender|vergabe|stahl|material/.test(role+' '+local))return name?'named_procurement':'functional_procurement';if(/project|projekt|technical|technik|engineer|engineering|konstruk/.test(role))return'named_project_technical';return name?'named_general':'generic_inbox';}
function explicitGermanGender(recipient,name){const raw=norm(first(recipient?.salutation,recipient?.honorific,recipient?.address_title,recipient?.title_prefix,recipient?.gender)),from=norm(name);if(/^(herr|mr|mister|male|mann|m|masculine)(\b|$)/.test(raw)||/^(herr|mr\.?|mister)\s+/.test(from))return'male';if(/^(frau|mrs|ms|miss|female|weiblich|w|f|feminine)(\b|$)/.test(raw)||/^(frau|mrs\.?|ms\.?|miss)\s+/.test(from))return'female';return'';}
function cleanPersonName(name){return txt(name,180).replace(/^(?:(?:herr|frau|mr\.?|mrs\.?|ms\.?|miss|prof\.?|dr\.?)\s+)+/i,'').replace(/\s+/g,' ').trim();}
function surname(name){const p=cleanPersonName(name).split(/\s+/).filter(Boolean);return p[p.length-1]||'';}
export function draftGreeting(language,recipient){const rr=recipientRole(recipient),name=rr==='generic_inbox'||rr==='functional_procurement'?'':cleanPersonName(recipient?.name),g=explicitGermanGender(recipient,recipient?.name),sn=surname(recipient?.name);if(language==='de'){if(g==='male'&&sn)return'Sehr geehrter Herr '+sn+',';if(g==='female'&&sn)return'Sehr geehrte Frau '+sn+',';return name?'Guten Tag '+name+',':'Sehr geehrte Damen und Herren,';}if(language==='bcs')return name?'Poštovani '+name+',':'Poštovani,';if(g==='male'&&sn)return'Dear Mr. '+sn+',';if(g==='female'&&sn)return'Dear Ms. '+sn+',';return name?'Dear '+name+',':'Dear Sir or Madam,';}
function closing(language){return language==='de'?'Mit freundlichen Grüßen':language==='bcs'?'S poštovanjem':'Kind regards';}
function resolveOfferModel(action,role){const motion=txt(action?.outreach_motion,80),route=txt(action?.route,80).toUpperCase(),stored=txt(action?.pristeel_offer_model,80),timing=txt(action?.timing_classification,80);if(role==='other_unclear'||(role==='unknown'&&action?.payload?.manual_draft_template)){const selected=action?.payload?.manual_draft_template;return selected==='gc_epc'?'fabricated_steel_package':selected==='steel_fabricator'?'external_production_capacity':'role_verification_required';}if(role==='trader_distributor')return'trader_fabrication_support';if(role==='steel_mill_producer')return'mill_downstream_fabrication';if(role==='consortium_jv')return'consortium_scope_support';if(role==='specialist_contractor')return'specialist_scope_support';if(motion==='future_supplier_qualification'||timing==='future_supplier_qualification'||stored==='future_supplier_qualification')return'future_supplier_qualification';if(route==='DIRECT_RAW_MATERIAL'||motion==='material_buyer'||stored==='material_supply'||role==='material_buyer')return'material_supply';if(role==='steel_fabricator'||route==='TED_PRODUCER'||motion==='external_production_capacity'||stored==='external_production_capacity')return'external_production_capacity';return'fabricated_steel_package';}
function deterministicVariant(seed,count){let h=2166136261;for(const ch of String(seed||'')){h^=ch.codePointAt(0)||0;h=Math.imul(h,16777619);}return Math.abs(h>>>0)%Math.max(1,count);}
export function controlledSubjectVariant(language,model,ctx,recipient,action,original){const producer=model==='external_production_capacity',gc=model==='fabricated_steel_package';if(!producer&&!gc)return original;const variants=language==='de'?(producer?['zusätzliche Fertigungskapazität','externe Produktionsunterstützung','Build-to-Print-Fertigungspartner']:['Stahlpaket','gefertigtes Stahlpaket','externe Unterstützung für Stahlpakete']):(producer?['additional fabrication capacity','external production support','build-to-print fabrication partner']:['steel package','fabricated steel package','external steel-package support']);const seed=[action?.id,action?.action_key,action?.target_company,recipient?.email,model].filter(Boolean).join('|'),label=variants[deterministicVariant(seed,variants.length)],anchor=ctx?.subject_anchor||ctx?.anchor||'';return [anchor,label].filter(Boolean).join(' – ')+' | PRISTEEL';}
function intro(language,ctx){const detail=[ctx.reference,ctx.package_code,ctx.unit,ctx.scope_label].filter(Boolean).join(' · ');if(language==='de')return`ich melde mich bezüglich ${detail?'des veröffentlichten Umfangs '+detail:'des Projekts '+ctx.anchor}.`;if(language==='bcs')return`javljam Vam se u vezi sa ${detail||ctx.anchor}.`;if(ctx.public_fact&&/Athalassa/i.test(ctx.public_fact))return`I am contacting you regarding the ${ctx.public_fact}.`;return`I am contacting you regarding ${detail||ctx.anchor}.`;}
function credibility(language,material=false){if(language==='de')return`PRISTEEL verbindet erfahrenes Stahlindustrie-Management mit einem etablierten ${material?'Beschaffungs- und Fertigungsnetzwerk':'Fertigungsnetzwerk'} in Südosteuropa. Wo vertraglich erforderlich, kann die Leistung über Bankgarantien der ProCredit Bank abgesichert werden.`;if(language==='bcs')return`PRISTEEL kombinuje iskusno upravljanje u industriji čelika sa etabliranom ${material?'mrežom dobavljača i proizvodnih partnera':'mrežom proizvodnih partnera'} u Jugoistočnoj Evropi. Kada je potrebno, ugovorno izvršenje može biti podržano bankarskim garancijama preko ProCredit Bank.`;return`PRISTEEL combines experienced steel-industry management with an established ${material?'steel supply and fabrication':'fabrication'} network in Southeast Europe. Where required, contractual performance can be supported by bank guarantees through ProCredit Bank.`;}
// Approved GC commercial paragraphs from pppp-gc-outreach/index.ts body1; keep wording aligned.
const APPROVED_GC_COMMERCIAL={
  "de": [
    "PRISTEEL kann die vollständige Verantwortung für ein klar definiertes Stahlpaket übernehmen – von Materialbeschaffung und Build-to-Print-Fertigung über Oberflächenschutz sowie Qualitäts- und Fertigungsdokumentation bis zur koordinierten DAP-Lieferung – mit einem technischen und kaufmännischen Ansprechpartner.",
    "Sie behalten die Kontrolle über das Projekt. Wir übernehmen das Stahlpaket von Zeichnungen oder Stückliste bis zur Lieferung.",
    "PRISTEEL verbindet erfahrenes Stahlindustrie-Management mit einem etablierten Fertigungsnetzwerk in Südosteuropa. Wo erforderlich, kann die Vertragserfüllung durch Bankgarantien der ProCredit Bank abgesichert werden.",
    "Wenn Sie ein konstruktives oder gefertigtes Stahlpaket lieber an einen externen Partner vergeben möchten, senden Sie uns die Zeichnungen oder Stückliste – wir übernehmen die weitere Abwicklung."
  ],
  "bcs": [
    "PRISTEEL može preuzeti punu odgovornost za jasno definisan čelični paket – od nabavke materijala i proizvodnje prema nacrtima do površinske zaštite, dokumentacije kvaliteta i proizvodnje i koordinirane DAP isporuke – preko jedne tehničke i komercijalne kontakt tačke.",
    "Vi zadržavate punu kontrolu nad projektom. Mi preuzimamo čelični paket od nacrta ili liste materijala do isporuke.",
    "PRISTEEL kombinuje iskusno upravljanje u industriji čelika sa etabliranom mrežom proizvodnih partnera u Jugoistočnoj Evropi. Kada je potrebno, ugovorno izvršenje može biti podržano bankarskim garancijama preko ProCredit Bank.",
    "Ako postoji konstrukcijski ili proizvodni čelični paket koji želite povjeriti jednom vanjskom partneru, pošaljite nam nacrte ili listu materijala i mi preuzimamo dalje."
  ],
  "en": [
    "PRISTEEL can take full responsibility for a clearly defined steel package — from material sourcing and build-to-print fabrication to surface treatment, quality and fabrication documentation, and coordinated DAP delivery — with one technical and commercial point of contact.",
    "You remain in control of the project. We take ownership of the steel package from drawings or BOM through to delivery.",
    "PRISTEEL combines experienced steel-industry management with an established fabrication network in Southeast Europe. Where required, contractual performance can be supported by bank guarantees through ProCredit Bank.",
    "If there is a structural or fabricated steel package you would prefer to place with one external partner, send us the drawings or BOM and we will take it from there."
  ]
};
function offerCopy(language,model,ctx,recipient,template=''){const p=intro(language,ctx),c=credibility(language,model==='material_supply'),a=ctx.subject_anchor,rr=recipientRole(recipient),referral=rr==='generic_inbox'?(language==='de'?'Falls eine andere Person dafür zuständig ist, freue ich mich über einen kurzen Hinweis auf den richtigen Kontakt.':language==='bcs'?'Ako je za ovaj opseg zadužena druga osoba, bio bih zahvalan na kontaktu.':'If another colleague is responsible for this scope, I would appreciate a referral.'):'';
 if(template==='gc_epc'&&model==='fabricated_steel_package'){
  const project=ctx.project_name,opening=language==='de'?`ich melde mich bezüglich des Projekts „${project}“.`:language==='bcs'?`javljam Vam se u vezi sa projektom „${project}“.`:`I am contacting you regarding “${project}”.`;
  return{subject:`${a}${ctx.scope_label?'':' – '+(language==='de'?'Stahlpaket':language==='bcs'?'čelični paket':'steel package')} | PRISTEEL`,paras:[opening,...APPROVED_GC_COMMERCIAL[language]]};
 }
 if(model==='external_production_capacity'){
  if(language==='de')return{subject:`${a} – externe Fertigungskapazität | PRISTEEL`,paras:[p,'Wenn Sie für klar definierte Pakete externe Fertigungskapazität einsetzen, kann PRISTEEL die technische Klärung, Build-to-Print-Fertigung, Oberflächenschutz, Qualitätsdokumentation und koordinierte DAP-Lieferung über einen Ansprechpartner übernehmen.','Ihr Team behält die Kontrolle über Projekt und Produktionsprioritäten; wir übernehmen die Abwicklung des ausgelagerten Pakets bis zur Lieferung.',c,'Nutzen Sie bei Kapazitätsspitzen externe Fertigung für klar abgegrenzte Pakete?',referral]};
  if(language==='bcs')return{subject:`${a} – vanjski proizvodni kapacitet | PRISTEEL`,paras:[p,'Ako koristite vanjski proizvodni kapacitet za jasno definisane pakete, PRISTEEL može koordinirati tehničko usaglašavanje, build-to-print proizvodnju, površinsku zaštitu, dokumentaciju kvaliteta i DAP isporuku.','Vaš tim zadržava kontrolu nad projektom i proizvodnim prioritetima; mi vodimo izdvojeni paket do isporuke.',c,'Koristite li vanjsku proizvodnju za jasno odvojene pakete u periodima većeg opterećenja?',referral]};
  return{subject:`${a} – external fabrication capacity | PRISTEEL`,paras:[p,'If you use external fabrication capacity for defined packages, PRISTEEL can coordinate technical clarification, build-to-print fabrication, surface treatment, quality documentation and DAP delivery through one point of contact.','Your team keeps control of the project and production priorities; we manage the outsourced package through delivery.',c,'Do you use external fabrication for clearly defined packages when internal capacity is constrained?',referral]};
 }
 if(model==='trader_fabrication_support'){
  if(language==='de')return{subject:`${a} – Fertigungs- und Bearbeitungspartner | PRISTEEL`,paras:[p,'Für projektbezogene Stahlpakete kann PRISTEEL externe Fertigung, Bearbeitung, Oberflächenschutz, Qualitätsdokumentation und koordinierte DAP-Lieferung übernehmen. Damit ergänzen wir Ihre Material- bzw. Handelsleistung, ohne vorauszusetzen, dass Sie selbst fertigen.',c,'Wenn Sie für dieses oder ähnliche Projekte gefertigte Komponenten extern zukaufen, senden Sie uns gerne Zeichnungen, Stückliste oder Materialliste.',referral]};
  if(language==='bcs')return{subject:`${a} – proizvodnja i obrada čelika | PRISTEEL`,paras:[p,'Za projektne čelične pakete PRISTEEL može preuzeti vanjsku proizvodnju, obradu, površinsku zaštitu, dokumentaciju kvaliteta i koordiniranu DAP isporuku. Time dopunjujemo Vašu trgovačku ili distributersku ulogu bez pretpostavke da proizvodite sami.',c,'Ako za ovaj ili slične projekte eksterno nabavljate gotove ili obrađene čelične komponente, pošaljite nam nacrte, BOM ili listu materijala.',referral]};
  return{subject:`${a} – fabrication and processing partner | PRISTEEL`,paras:[p,'For project-specific steel packages, PRISTEEL can provide outsourced fabrication, processing, surface treatment, quality documentation and coordinated DAP delivery. This complements your trading or distribution role without assuming that you fabricate in-house.',c,'If you source fabricated or processed steel components externally for this or similar projects, send us the drawings, BOM or material list.',referral]};
 }
 if(model==='mill_downstream_fabrication'){
  if(language==='de')return{subject:`${a} – Weiterverarbeitung / Projektfertigung | PRISTEEL`,paras:[p,'PRISTEEL bietet Ihnen keine Standard-Stahlversorgung an. Wir können Ihr Material dort ergänzen, wo ein Projekt nachgelagerte Build-to-Print-Fertigung, Baugruppen, Oberflächenschutz, Qualitätsdokumentation und koordinierte DAP-Lieferung verlangt.',c,'Falls Kunden von Ihnen neben dem Vormaterial auch ein fertigungsnahes Projektpaket benötigen, prüfen wir gerne einen klar abgegrenzten Umfang.',referral]};
  if(language==='bcs')return{subject:`${a} – dalja obrada / projektna proizvodnja | PRISTEEL`,paras:[p,'PRISTEEL Vam ne nudi standardnu isporuku čelika. Možemo dopuniti Vaš materijal tamo gdje projekt zahtijeva dalju build-to-print proizvodnju, sklopove, površinsku zaštitu, dokumentaciju kvaliteta i koordiniranu DAP isporuku.',c,'Ako Vaši kupci uz osnovni materijal traže i jasno definisan proizvodni paket, rado ćemo pregledati takav opseg.',referral]};
  return{subject:`${a} – downstream fabrication support | PRISTEEL`,paras:[p,'PRISTEEL is not approaching you with a commodity steel-supply offer. We can complement your material where a project requires downstream build-to-print fabrication, assemblies, surface treatment, quality documentation and coordinated DAP delivery.',c,'If your customers need a defined fabricated project package in addition to mill material, we would be glad to review that scope.',referral]};
 }
 if(model==='consortium_scope_support'){
  if(language==='de')return{subject:`${a} – Stahlpaket / zuständiger Konsortialpartner | PRISTEEL`,paras:[p,'Bei einem Konsortium möchten wir die Rollen nicht vermischen. PRISTEEL kann einen klar abgegrenzten Stahlbau- oder Fertigungsumfang übernehmen, sobald feststeht, welcher Konsortialpartner dafür verantwortlich ist.',c,'Könnten Sie uns bitte an die Person bzw. das Konsortialmitglied verweisen, das für Stahlbau, Metallbau oder die entsprechende Material-/Fertigungspaketierung zuständig ist?',referral]};
  if(language==='bcs')return{subject:`${a} – čelični paket / odgovorni član konzorcija | PRISTEEL`,paras:[p,'Kod konzorcija ne želimo miješati uloge članova. PRISTEEL može preuzeti jasno definisan čelični ili proizvodni paket čim se potvrdi koji član konzorcija je za njega odgovoran.',c,'Molimo Vas da nas uputite na osobu ili člana konzorcija odgovornog za čelične konstrukcije, metalne radove ili odgovarajući paket materijala/proizvodnje.',referral]};
  return{subject:`${a} – steel scope / responsible consortium member | PRISTEEL`,paras:[p,'For a consortium, we do not want to assume that all members have the same role. PRISTEEL can support a clearly defined steel or fabrication package once the member responsible for that scope is identified.',c,'Could you please point us to the person or consortium member responsible for structural steel, metalwork or the related material/fabrication package?',referral]};
 }
 if(model==='specialist_scope_support'){
  if(language==='de')return{subject:`${a} – Fertigungsunterstützung für den Fachlosumfang | PRISTEEL`,paras:[p,'Für Ihren Fachlosumfang kann PRISTEEL klar abgegrenzte Stahl- oder Metallkomponenten nach freigegebenen Zeichnungen fertigen, dokumentieren und DAP liefern. Wir adressieren nur den tatsächlich relevanten Fertigungsanteil und nicht Ihr gesamtes Gewerk.',c,'Wenn innerhalb des Loses ein extern vergebbarer Stahl-/Metallbauanteil besteht, senden Sie uns gerne die entsprechenden Zeichnungen oder die Stückliste.',referral]};
  if(language==='bcs')return{subject:`${a} – proizvodna podrška za specijalistički paket | PRISTEEL`,paras:[p,'Za Vaš specijalistički paket PRISTEEL može proizvesti, dokumentovati i DAP isporučiti jasno odvojene čelične ili metalne komponente prema odobrenim nacrtima. Fokusiramo se samo na stvarno relevantan proizvodni dio, ne na kompletan Vaš trade scope.',c,'Ako unutar paketa postoji čelični/metalni dio koji se može eksterno proizvesti, pošaljite nam odgovarajuće nacrte ili BOM.',referral]};
  return{subject:`${a} – fabrication support for specialist package | PRISTEEL`,paras:[p,'For your specialist package, PRISTEEL can fabricate, document and DAP-deliver clearly separated steel or metal components to approved drawings. We address only the relevant fabrication scope rather than assuming responsibility for your complete trade package.',c,'If the package contains a steel/metal component scope suitable for external fabrication, send us the relevant drawings or BOM.',referral]};
 }
 if(model==='material_supply'){
  if(language==='de')return{subject:`${a} – Stahlmaterial | PRISTEEL`,paras:[p,ctx.materials.length?`Für den veröffentlichten Umfang sind folgende Materialangaben erkennbar: ${ctx.materials.join(', ')}. PRISTEEL kann die Beschaffung, Dokumentation und DAP-Lieferung eines bestätigten Materialpakets koordinieren.`:'Sobald eine freigegebene Materialliste vorliegt, kann PRISTEEL die Beschaffung, EN-10204-3.1-Dokumentation, optionale Bearbeitung und DAP-Lieferung des bestätigten Materialpakets koordinieren.',c,'Senden Sie uns dafür gerne die aktuelle RFQ oder Materialliste mit Lieferort.',referral]};
  if(language==='bcs')return{subject:`${a} – čelični materijal | PRISTEEL`,paras:[p,'PRISTEEL koordinira projektne pakete čeličnog materijala iz kvalifikovanih izvora – profile, limove i cijevi/šuplje profile sa EN 10204 3.1 dokumentacijom, opcionom obradom i DAP isporukom preko jedne kontakt tačke.',c,'Ako nabavljate ovu kategoriju materijala, pošaljite nam aktuelni RFQ ili listu materijala i mjesto isporuke.',referral]};
  return{subject:`${a} – steel material | PRISTEEL`,paras:[p,'PRISTEEL coordinates project-specific steel material from qualified sources — sections, plates and tubes/hollow sections with EN 10204 3.1 documentation, optional processing and DAP delivery through one commercial contact.',c,'If you purchase this material category, send us one current RFQ or material list and the delivery point.',referral]};
 }
 if(model==='future_supplier_qualification'){
  if(language==='de')return{subject:`${a} – Lieferantenqualifizierung Stahl | PRISTEEL`,paras:['ich melde mich im Hinblick auf künftige Stahlpakete.','PRISTEEL kann für klar definierte Umfänge Materialbeschaffung, Build-to-Print-Fertigung, Oberflächenschutz, Qualitätsdokumentation und DAP-Lieferung über einen technischen und kaufmännischen Ansprechpartner koordinieren.',c,'Wer ist bei Ihnen für die Qualifizierung künftiger Partner für Stahlpakete zuständig?',referral]};
  if(language==='bcs')return{subject:`${a} – kvalifikacija dobavljača čelika | PRISTEEL`,paras:['javljam Vam se u vezi sa budućim čeličnim paketima.','PRISTEEL može za jasno definisane opsege koordinirati nabavku materijala, build-to-print proizvodnju, površinsku zaštitu, dokumentaciju kvaliteta i DAP isporuku preko jedne tehničke i komercijalne kontakt tačke.',c,'Ko je kod Vas zadužen za kvalifikaciju budućih partnera za čelične pakete?',referral]};
  return{subject:`${a} – future steel partner qualification | PRISTEEL`,paras:['I am contacting you regarding future steel packages.','For clearly defined scopes, PRISTEEL can coordinate material sourcing, build-to-print fabrication, surface treatment, quality documentation and DAP delivery through one technical and commercial point of contact.',c,'Who handles qualification of future partners for steel packages?',referral]};
 }
 if(language==='de'){const known=ctx.components.length?`Aus der Bekanntmachung sind ${ctx.components.join(', ')} als Bestandteile des Umfangs erkennbar.`:'';const capability=ctx.package_kind==='metal_doors'?'Soweit für diesen Umfang externe Fertigungs- oder Lieferanteile vorgesehen sind, kann PRISTEEL klar abgegrenzte Metallkomponenten oder Baugruppen nach freigegebenen Zeichnungen koordinieren.':ctx.package_kind==='structural_metalwork'?'Soweit für diesen Umfang ein externes Fertigungs- oder Lieferpaket vorgesehen ist, kann PRISTEEL klar abgegrenzte Stahlbaukomponenten nach freigegebenen Zeichnungen koordinieren.':'Soweit ein klar abgegrenztes externes Stahlpaket vorgesehen ist, kann PRISTEEL dessen technische und kaufmännische Abwicklung bis zur DAP-Lieferung koordinieren.';return{subject:`${a} | PRISTEEL`,paras:[p,known,capability,c,'Falls dies für das genannte Paket relevant ist, senden Sie uns gerne die aktuellen Zeichnungen, Stückliste oder Materialliste zur Prüfung.',referral]};}
 if(language==='bcs')return{subject:`${a}${ctx.scope_label?'':' – čelični paket'} | PRISTEEL`,paras:[p,'PRISTEEL može preuzeti tehničku i komercijalnu realizaciju jasno definisanog čeličnog paketa – od nabavke materijala i build-to-print proizvodnje do površinske zaštite, dokumentacije kvaliteta i koordinirane DAP isporuke.','Upravljanje projektom ostaje kod Vas; mi vodimo ugovoreni čelični paket od nacrta ili liste materijala do isporuke.',c,'Ako postoji jasno odvojen čelični ili proizvodni paket za vanjskog partnera, pošaljite nam nacrte ili listu materijala – mi preuzimamo dalje.',referral]};
 return{subject:`${a}${ctx.scope_label?'':' – steel package'} | PRISTEEL`,paras:[p,'PRISTEEL can take full responsibility for a clearly defined steel package — from material sourcing and build-to-print fabrication to surface treatment, quality documentation and coordinated DAP delivery — with one technical and commercial point of contact.','You remain in control of the project. We take ownership of the steel package from drawings or BOM through delivery.',c,'If there is a structural or fabricated steel package you would prefer to place with one external partner, send us the drawings or BOM and we will take it from there.',referral]};
}
function htmlParagraph(v){return v?`<p style="margin:0 0 14px 0">${esc(v)}</p>`:'';}
export function buildTedDraftContent(action={},tender={},recipient={}){const language=resolveDraftLanguage(action,tender,recipient),role=companyRole(action,tender);const selected=['other_unclear','unknown'].includes(role)?action?.payload?.manual_draft_template:null;if(role==='other_unclear'&&!['gc_epc','steel_fabricator'].includes(selected))throw new Error('company_role_verification_required');const ctx=projectContext(action,tender,language),offerModel=resolveOfferModel(action,role),template=selected||((role==='gc_epc'&&offerModel==='fabricated_steel_package')?'gc_epc':offerModel==='external_production_capacity'?'steel_fabricator':null),copy=offerCopy(language,offerModel,ctx,recipient,template),subject=controlledSubjectVariant(language,offerModel,ctx,recipient,action,copy.subject),hello=draftGreeting(language,recipient),close=template==='gc_epc'?(language==='de'?'Mit freundlichen Grüßen,':language==='bcs'?'Srdačan pozdrav,':'Kind regards,'):closing(language),paras=copy.paras.filter(Boolean),plainBody=[hello,...paras,close,SIGNATURE].join('\n\n'),htmlBody='<div dir="ltr" style="font-family:Arial,sans-serif;font-size:14px;line-height:1.5;color:#202124">'+htmlParagraph(hello)+paras.map(htmlParagraph).join('')+`<p style="margin:0">${esc(close)}</p>`+SIGNATURE_HTML+'</div>',offerReason=selected?'Approved template selected manually for this draft; the company role remains unverified.':role==='unknown'?'Company role is not yet verified; use a cautious package-specific introduction without assuming materials or delivery responsibility.':`Offer selected from verified company role ${role} and published package scope.`;return{subject,plain_body:plainBody,html_body:htmlBody,offer_model:offerModel,approved_template:template,template_selected_manually:!!selected,company_role:role,recipient_role:recipientRole(recipient),selected_public_facts:ctx.verified_facts,missing_facts:ctx.missing_facts,offer_reason:offerReason,package_identity:{reference:ctx.reference||null,package_code:ctx.package_code||null,unit:ctx.unit||null,scope_label:ctx.scope_label||null,source_value:ctx.value||null,complete:ctx.package_complete},copy_policy_version:COPY_POLICY_VERSION,language,body:plainBody,recipient_kind:recipientRole(recipient)==='generic_inbox'?'general':'direct',tender_reference:tedReference(tender)||null,tender_url:tedUrl(tender)||null,signature:SIGNATURE,signature_html:SIGNATURE_HTML};}
export const PRISTEEL_SIGNATURE=SIGNATURE;
export const PRISTEEL_SIGNATURE_HTML=SIGNATURE_HTML;

