import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')!;
const GMAIL_USER=Deno.env.get('GMAIL_USER')!;
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-pppp-cron-secret','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Content-Type':'application/json'};
const text=(v:any,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);

function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;const sa=JSON.parse(SA_JSON),scope='https://www.googleapis.com/auth/gmail.compose',header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),data=await r.json();if(!r.ok)throw new Error(`token ${r.status}: ${JSON.stringify(data).slice(0,400)}`);cachedToken={token:data.access_token,exp:now+(data.expires_in||3600)};return cachedToken.token;}
async function authorized(req:Request){const provided=req.headers.get('x-pppp-cron-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided});return !error&&data===true;}
function headerSafe(v:any){return text(v,500).replace(/[\r\n]+/g,' ');}
function bodyFor(a:any){const company=text(a.target_company,300)||'there',tender=text(a.tender_title,500),buyer=text(a.authority,300),brief=text(a.draft_brief,5000),route=text(a.route,80);if(route==='TED_GC')return `Dear ${company} team,\n\nWe noted the public award of the project “${tender}”${buyer?` for ${buyer}`:''}.\n\nPriSteel is a structural-steel fabrication company and we would be interested in supporting your team on relevant steel packages for this project, including fabrication and related production capacity where useful.\n\n${brief}\n\nIf this is relevant to your procurement/project team, we would be glad to review the applicable steel scope and discuss how PriSteel could support the execution.\n\nBest regards,\nPriSteel`;
if(route==='TED_PRODUCER')return `Dear ${company} team,\n\nWe noted the public award related to “${tender}”.\n\nPriSteel would like to offer additional fabrication capacity to complement your own production when workload, delivery schedules or specific packages require extra capacity. We can support structural-steel fabrication and coordinated production according to project requirements.\n\n${brief}\n\nIf useful, we would be glad to discuss the packages or production capacity where we could support your team.\n\nBest regards,\nPriSteel`;
return `${brief}\n\nBest regards,\nPriSteel`;}
async function createDraft(a:any){const raw=[`To: ${headerSafe(a.target_email)}`,`Subject: ${headerSafe(a.subject_hint||`PriSteel · ${a.tender_title||'Opportunity'}`)}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit','',bodyFor(a)].join('\r\n'),tk=await token(),r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts`,{method:'POST',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify({message:{raw:b64url(raw)}})}),data=await r.json();if(!r.ok)throw new Error(`Gmail draft ${r.status}: ${JSON.stringify(data).slice(0,600)}`);return data;}
async function run(limit=20){const {data,error}=await db.from('pppp_opportunity_action_queue_v2').select('*').eq('status','draft_review').in('action_type',['gc_project_outreach_draft','producer_capacity_outreach_draft']).not('target_email','is',null).order('updated_at',{ascending:true}).limit(Math.min(50,Math.max(1,limit)));if(error)throw error;let created=0,skipped=0,precisionBlocked=0,failed=0;const errors:any[]=[];for(const a of data||[]){const p=a.payload&&typeof a.payload==='object'?a.payload:{};if(p?.precision_gate?.ready!==true||p?.precision_gate?.disposition!=='draft_review'){precisionBlocked++;continue;}if(p.gmail_draft_id){skipped++;continue;}try{const d=await createDraft(a),next={...p,gmail_draft_id:d.id,gmail_message_id:d.message?.id||null,gmail_thread_id:d.message?.threadId||null,gmail_draft_created_at:new Date().toISOString(),gmail_draft_generator:'pppp-opportunity-draft-generator-v2-precision-gated',human_send_required:true};const {error:e}=await db.from('pppp_opportunity_actions').update({payload:next,updated_at:new Date().toISOString()}).eq('id',a.id);if(e)throw e;created++;}catch(e){failed++;errors.push({action_key:a.action_key,error:String(e).slice(0,500)});}}return{candidates:(data||[]).length,created,skipped,precision_blocked:precisionBlocked,failed,errors:errors.slice(0,10)};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!(await authorized(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:cors});try{const u=new URL(req.url),limit=Number(u.searchParams.get('limit')||20),out=await run(limit);return new Response(JSON.stringify({ok:true,...out}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e)}),{status:500,headers:cors});}});
