import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { resolveTedRecipients, normalizeEmail } from "./recipient-policy.mjs";
import { encodeRfc2047Header } from "./mime-headers.mjs";
import { buildTedDraftContent } from "./draft-content.mjs";

const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')!;
const GMAIL_USER=Deno.env.get('GMAIL_USER')!;
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-pppp-cron-secret','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Content-Type':'application/json'};
const text=(v:any,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);
const GENERATOR='pppp-opportunity-draft-generator-v3-language-ted-signature';
const MAX_CONTACTS_PER_ACTION=20;
const MAX_DRAFT_WRITES_PER_RUN=60;

function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;const sa=JSON.parse(SA_JSON),scope='https://www.googleapis.com/auth/gmail.compose',header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})}),data=await r.json();if(!r.ok)throw new Error(`token ${r.status}: ${JSON.stringify(data).slice(0,400)}`);cachedToken={token:data.access_token,exp:now+(data.expires_in||3600)};return cachedToken.token;}
async function authorized(req:Request){const provided=req.headers.get('x-pppp-cron-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided});return !error&&data===true;}
function headerSafe(v:any){return text(v,500).replace(/[\r\n]+/g,' ');}

async function tenderContext(tenderWatchId:any){const id=text(tenderWatchId,80);if(!id)return{};const {data,error}=await db.from('kek_tender_watch').select('payload,publication_no,procurement_no,source_url,detail_url,title,authority').eq('id',id).maybeSingle();if(error)throw error;const p=data?.payload&&typeof data.payload==='object'?data.payload:{};return{...p,publication_no:data?.publication_no||p.publication_no||null,procurement_no:data?.procurement_no||p.procurement_no||null,source_url:data?.source_url||p.source_url||null,detail_url:data?.detail_url||p.detail_url||null,title:data?.title||p.title||null,authority:data?.authority||p.authority||null};}
function rawFor(a:any,tender:any,recipient:any){const content=buildTedDraftContent(a,tender,recipient),to=normalizeEmail(recipient?.email);if(!to)throw new Error('recipient_email_required');const raw=[`To: ${headerSafe(to)}`,`Subject: ${encodeRfc2047Header(content.subject)}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit','',content.body].join('\r\n');return{raw,content,to};}
async function writeDraft(a:any,tender:any,recipient:any,draftId=''){const built=rawFor(a,tender,recipient),tk=await token(),url=`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts${draftId?`/${encodeURIComponent(draftId)}`:''}`,r=await fetch(url,{method:draftId?'PUT':'POST',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify({message:{raw:b64url(built.raw)}})}),data=await r.json();if(!r.ok)throw new Error(`Gmail draft ${r.status}: ${JSON.stringify(data).slice(0,600)}`);return{data,content:built.content,to:built.to};}

function existingDrafts(a:any,p:any){const out:any[]=[],seen=new Set<string>();for(const d of Array.isArray(p?.gmail_drafts)?p.gmail_drafts:[]){const email=normalizeEmail(d?.email);if(!email||seen.has(email)||!d?.draft_id)continue;seen.add(email);out.push({...d,email});}const legacy=normalizeEmail(a?.target_email);if(p?.gmail_draft_id&&legacy&&!seen.has(legacy)){seen.add(legacy);out.push({email:legacy,name:null,job_title:null,draft_id:p.gmail_draft_id,message_id:p.gmail_message_id||null,thread_id:p.gmail_thread_id||null,created_at:p.gmail_draft_created_at||null,legacy:true});}return out;}
function draftCurrent(d:any,a:any,tender:any,recipient:any){if(!d||d.generator!==GENERATOR)return false;const c=buildTedDraftContent(a,tender,recipient);return d.language===c.language&&String(d.tender_reference||'')===String(c.tender_reference||'')&&String(d.subject||'')===String(c.subject||'');}
async function persistDraftState(a:any,p:any,drafts:any[],recipients:any[],tender:any){const first=drafts[0]||null,byEmail=new Map(drafts.map((d:any)=>[normalizeEmail(d.email),d])),allCurrent=recipients.every((r:any)=>draftCurrent(byEmail.get(normalizeEmail(r.email)),a,tender,r));const next={...p,gmail_drafts:drafts,gmail_draft_count:drafts.length,gmail_recipient_count:recipients.length,gmail_recipients:recipients.map((r:any)=>({email:r.email,name:r.name||null,job_title:r.job_title||null,purpose:r.purpose||null,confidence:r.confidence||null,source_type:r.source_type||null})),gmail_draft_generator_target:GENERATOR,gmail_draft_generator_complete:allCurrent,gmail_draft_generator:allCurrent?GENERATOR:(p.gmail_draft_generator||null),gmail_auto_send:false,human_send_required:true,...(first?{gmail_draft_id:first.draft_id,gmail_message_id:first.message_id||null,gmail_thread_id:first.thread_id||null,gmail_draft_created_at:first.created_at||p.gmail_draft_created_at||new Date().toISOString()}:{} )};const {error}=await db.from('pppp_opportunity_actions').update({payload:next,updated_at:new Date().toISOString()}).eq('id',a.id);if(error)throw error;return next;}

async function processAction(a:any,budget:{writes:number}){let p=a.payload&&typeof a.payload==='object'?a.payload:{},tender=await tenderContext(a.tender_watch_id);const recipients=/^TED_/i.test(text(a.route,80))?resolveTedRecipients(a,tender,MAX_CONTACTS_PER_ACTION):resolveTedRecipients(a,{winner:{email:a.target_email}},1);if(!recipients.length)return{action_key:a.action_key,event:'no_recipients',recipients:0,created:0,updated:0,existing:0};
  let drafts=existingDrafts(a,p),byEmail=new Map(drafts.map((d:any)=>[normalizeEmail(d.email),d])),created=0,updated=0,failures:any[]=[];
  for(const recipient of recipients){const email=normalizeEmail(recipient.email),old=byEmail.get(email);if(draftCurrent(old,a,tender,recipient))continue;if(budget.writes>=MAX_DRAFT_WRITES_PER_RUN)break;try{const d=await writeDraft(a,tender,recipient,old?.draft_id||''),at=new Date().toISOString(),row={...(old||{}),email,name:recipient.name||null,job_title:recipient.job_title||null,purpose:recipient.purpose||null,confidence:recipient.confidence||null,source_type:recipient.source_type||null,source_url:recipient.source_url||null,draft_id:d.data.id||old?.draft_id,message_id:d.data.message?.id||old?.message_id||null,thread_id:d.data.message?.threadId||old?.thread_id||null,created_at:old?.created_at||at,updated_at:at,generator:GENERATOR,language:d.content.language,tender_reference:d.content.tender_reference,tender_url:d.content.tender_url,subject:d.content.subject};if(old){const i=drafts.findIndex((x:any)=>normalizeEmail(x.email)===email);if(i>=0)drafts[i]=row;else drafts.push(row);updated++;}else{drafts.push(row);created++;}byEmail.set(email,row);budget.writes++;p=await persistDraftState(a,p,drafts,recipients,tender);}catch(e){failures.push({email,operation:old?'update':'create',error:String(e).slice(0,400)});}}
  p=await persistDraftState(a,p,drafts,recipients,tender);byEmail=new Map(drafts.map((d:any)=>[normalizeEmail(d.email),d]));const current=recipients.filter((r:any)=>draftCurrent(byEmail.get(normalizeEmail(r.email)),a,tender,r)).length;
  return{action_key:a.action_key,company:a.target_company,event:current>=recipients.length?'drafts_ready':'drafts_partial',recipients:recipients.length,created,updated,existing:Math.max(0,drafts.length-created),current,remaining:Math.max(0,recipients.length-current),failures};
}

async function run(limit=20,actionId=''){let q=db.from('pppp_opportunity_action_queue_v2').select('*').eq('status','draft_review').in('action_type',['gc_project_outreach_draft','producer_capacity_outreach_draft']).order('updated_at',{ascending:true});if(text(actionId,80))q=q.eq('id',text(actionId,80));const {data,error}=await q.limit(Math.min(50,Math.max(1,limit)));if(error)throw error;const budget={writes:0},results:any[]=[],errors:any[]=[];let actionsReady=0,actionsPartial=0,noRecipients=0,created=0,updated=0,existing=0;for(const a of data||[]){try{const r=await processAction(a,budget);results.push(r);created+=Number(r.created||0);updated+=Number(r.updated||0);existing+=Number(r.existing||0);if(r.event==='drafts_ready')actionsReady++;else if(r.event==='drafts_partial')actionsPartial++;else if(r.event==='no_recipients')noRecipients++;if(budget.writes>=MAX_DRAFT_WRITES_PER_RUN)break;}catch(e){errors.push({action_key:a.action_key,error:String(e).slice(0,500)});}}
return{candidates:(data||[]).length,actions_ready:actionsReady,actions_partial:actionsPartial,no_recipients:noRecipients,drafts_created:created,drafts_updated:updated,draft_writes:budget.writes,drafts_existing:existing,failed:errors.length,errors:errors.slice(0,10),results:results.slice(0,50),generator:GENERATOR,separate_draft_per_recipient:true,human_send_required:true,auto_send:false,max_contacts_per_action:MAX_CONTACTS_PER_ACTION,draft_write_budget_per_run:MAX_DRAFT_WRITES_PER_RUN};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!(await authorized(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:cors});try{const u=new URL(req.url),limit=Number(u.searchParams.get('limit')||20),actionId=text(u.searchParams.get('action_id')||'',80),out=await run(limit,actionId);return new Response(JSON.stringify({ok:true,...out}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e),auto_send:false,human_send_required:true}),{status:500,headers:cors});}});
