import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
import { resolveTedRecipients, recipientGreeting, normalizeEmail } from "./recipient-policy.mjs";
import { encodeRfc2047Header } from "./mime-headers.mjs";

const SA_JSON=Deno.env.get('GOOGLE_SA_JSON')!;
const GMAIL_USER=Deno.env.get('GMAIL_USER')!;
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-pppp-cron-secret','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Content-Type':'application/json'};
const text=(v:any,max=12000)=>String(v==null?'':v).replace(/\r/g,'').trim().slice(0,max);
const GENERATOR='pppp-opportunity-draft-generator-v2-multi-contact';
const MAX_CONTACTS_PER_ACTION=20;
const MAX_NEW_DRAFTS_PER_RUN=60;

function b64url(input:Uint8Array|string){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let bin='';for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function pemToArrayBuffer(pem:string){const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s+/g,'');const bin=atob(body),buf=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)buf[i]=bin.charCodeAt(i);return buf.buffer;}
let cachedToken:{token:string;exp:number}|null=null;
async function token(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;const sa=JSON.parse(SA_JSON),scope='https://www.googleapis.com/auth/gmail.compose',header={alg:'RS256',typ:'JWT'},claim={iss:sa.client_email,sub:GMAIL_USER,scope,aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600},unsigned=`${b64url(JSON.stringify(header))}.${b64url(JSON.stringify(claim))}`;const key=await crypto.subtle.importKey('pkcs8',pemToArrayBuffer(sa.private_key),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned))),jwt=`${unsigned}.${b64url(sig)}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth-grant-type:jwt-bearer',assertion:jwt})}),data=await r.json();if(!r.ok)throw new Error(`token ${r.status}: ${JSON.stringify(data).slice(0,400)}`);cachedToken={token:data.access_token,exp:now+(data.expires_in||3600)};return cachedToken.token;}
async function authorized(req:Request){const provided=req.headers.get('x-pppp-cron-secret')||'';if(!provided)return false;const {data,error}=await db.rpc('gmail_tracker_cron_authorized',{provided});return !error&&data===true;}
function headerSafe(v:any){return text(v,500).replace(/[\r\n]+/g,' ');}

function bodyFor(a:any,recipient:any){const company=text(a.target_company,300)||'there',tender=text(a.tender_title,500),buyer=text(a.authority,300),brief=text(a.draft_brief,5000),route=text(a.route,80),greeting=recipientGreeting(company,recipient);if(route==='TED_GC')return `${greeting}\n\nWe noted the public award of the project “${tender}”${buyer?` for ${buyer}`:''}.\n\nPriSteel is a structural-steel fabrication company and we would be interested in supporting your team on relevant steel packages for this project, including fabrication and related production capacity where useful.\n\n${brief}\n\nIf this is relevant to your procurement/project team, we would be glad to review the applicable steel scope and discuss how PriSteel could support the execution.\n\nBest regards,\nPriSteel`;
if(route==='TED_PRODUCER')return `${greeting}\n\nWe noted the public award related to “${tender}”.\n\nPriSteel would like to offer additional fabrication capacity to complement your own production when workload, delivery schedules or specific packages require extra capacity. We can support structural-steel fabrication and coordinated production according to project requirements.\n\n${brief}\n\nIf useful, we would be glad to discuss the packages or production capacity where we could support your team.\n\nBest regards,\nPriSteel`;
return `${greeting}\n\n${brief}\n\nBest regards,\nPriSteel`;}
async function createDraft(a:any,recipient:any){const to=normalizeEmail(recipient?.email);if(!to)throw new Error('recipient_email_required');const raw=[`To: ${headerSafe(to)}`,`Subject: ${encodeRfc2047Header(a.subject_hint||`PriSteel · ${a.tender_title||'Opportunity'}`)}`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: 8bit','',bodyFor(a,recipient)].join('\r\n'),tk=await token(),r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(GMAIL_USER)}/drafts`,{method:'POST',headers:{Authorization:`Bearer ${tk}`,'Content-Type':'application/json'},body:JSON.stringify({message:{raw:b64url(raw)}})}),data=await r.json();if(!r.ok)throw new Error(`Gmail draft ${r.status}: ${JSON.stringify(data).slice(0,600)}`);return data;}

async function tenderPayload(tenderWatchId:any){const id=text(tenderWatchId,80);if(!id)return{};const {data,error}=await db.from('kek_tender_watch').select('payload').eq('id',id).maybeSingle();if(error)throw error;return data?.payload&&typeof data.payload==='object'?data.payload:{};}
function existingDrafts(a:any,p:any){const out:any[]=[],seen=new Set<string>();for(const d of Array.isArray(p?.gmail_drafts)?p.gmail_drafts:[]){const email=normalizeEmail(d?.email);if(!email||seen.has(email)||!d?.draft_id)continue;seen.add(email);out.push({...d,email});}const legacy=normalizeEmail(a?.target_email);if(p?.gmail_draft_id&&legacy&&!seen.has(legacy)){seen.add(legacy);out.push({email:legacy,name:null,job_title:null,draft_id:p.gmail_draft_id,message_id:p.gmail_message_id||null,thread_id:p.gmail_thread_id||null,created_at:p.gmail_draft_created_at||null,legacy:true});}return out;}
async function persistDraftState(a:any,p:any,drafts:any[],recipients:any[]){const first=drafts[0]||null,next={...p,gmail_drafts:drafts,gmail_draft_count:drafts.length,gmail_recipient_count:recipients.length,gmail_recipients:recipients.map((r:any)=>({email:r.email,name:r.name||null,job_title:r.job_title||null,purpose:r.purpose||null,confidence:r.confidence||null,source_type:r.source_type||null})),gmail_draft_generator:GENERATOR,human_send_required:true,...(!p.gmail_draft_id&&first?{gmail_draft_id:first.draft_id,gmail_message_id:first.message_id||null,gmail_thread_id:first.thread_id||null,gmail_draft_created_at:first.created_at||new Date().toISOString()}:{} )};const {error}=await db.from('pppp_opportunity_actions').update({payload:next,updated_at:new Date().toISOString()}).eq('id',a.id);if(error)throw error;return next;}

async function processAction(a:any,budget:{newDrafts:number}){let p=a.payload&&typeof a.payload==='object'?a.payload:{},winnerPayload=await tenderPayload(a.tender_watch_id);let recipients=/^TED_/i.test(text(a.route,80))?resolveTedRecipients(a,winnerPayload,MAX_CONTACTS_PER_ACTION):resolveTedRecipients(a,{winner:{email:a.target_email}},1);if(!recipients.length)return{action_key:a.action_key,event:'no_recipients',recipients:0,created:0,existing:0};
  let drafts=existingDrafts(a,p),known=new Set(drafts.map((d:any)=>normalizeEmail(d.email))),created=0,failures:any[]=[];
  for(const recipient of recipients){const email=normalizeEmail(recipient.email);if(known.has(email))continue;if(budget.newDrafts>=MAX_NEW_DRAFTS_PER_RUN)break;try{const d=await createDraft(a,recipient),at=new Date().toISOString(),row={email,name:recipient.name||null,job_title:recipient.job_title||null,purpose:recipient.purpose||null,confidence:recipient.confidence||null,source_type:recipient.source_type||null,source_url:recipient.source_url||null,draft_id:d.id,message_id:d.message?.id||null,thread_id:d.message?.threadId||null,created_at:at};drafts.push(row);known.add(email);created++;budget.newDrafts++;p=await persistDraftState(a,p,drafts,recipients);}catch(e){failures.push({email,error:String(e).slice(0,400)});}}
  if(!created){p=await persistDraftState(a,p,drafts,recipients);}
  return{action_key:a.action_key,company:a.target_company,event:known.size>=recipients.length?'drafts_ready':'drafts_partial',recipients:recipients.length,created,existing:drafts.length-created,remaining:Math.max(0,recipients.length-known.size),failures};
}

async function run(limit=20,actionId=''){let q=db.from('pppp_opportunity_action_queue_v2').select('*').eq('status','draft_review').in('action_type',['gc_project_outreach_draft','producer_capacity_outreach_draft']).order('updated_at',{ascending:true});if(text(actionId,80))q=q.eq('id',text(actionId,80));const {data,error}=await q.limit(Math.min(50,Math.max(1,limit)));if(error)throw error;const budget={newDrafts:0},results:any[]=[],errors:any[]=[];let actionsReady=0,actionsPartial=0,noRecipients=0,existing=0;for(const a of data||[]){try{const r=await processAction(a,budget);results.push(r);existing+=Number(r.existing||0);if(r.event==='drafts_ready')actionsReady++;else if(r.event==='drafts_partial')actionsPartial++;else if(r.event==='no_recipients')noRecipients++;if(budget.newDrafts>=MAX_NEW_DRAFTS_PER_RUN)break;}catch(e){errors.push({action_key:a.action_key,error:String(e).slice(0,500)});}}
return{candidates:(data||[]).length,actions_ready:actionsReady,actions_partial:actionsPartial,no_recipients:noRecipients,drafts_created:budget.newDrafts,drafts_existing:existing,failed:errors.length,errors:errors.slice(0,10),results:results.slice(0,50),separate_draft_per_recipient:true,human_send_required:true,auto_send:false,max_contacts_per_action:MAX_CONTACTS_PER_ACTION,draft_budget_per_run:MAX_NEW_DRAFTS_PER_RUN};}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!(await authorized(req)))return new Response(JSON.stringify({ok:false,error:'unauthorized'}),{status:401,headers:cors});try{const u=new URL(req.url),limit=Number(u.searchParams.get('limit')||20),actionId=text(u.searchParams.get('action_id')||'',80),out=await run(limit,actionId);return new Response(JSON.stringify({ok:true,...out}),{headers:cors});}catch(e){return new Response(JSON.stringify({ok:false,error:String(e),auto_send:false,human_send_required:true}),{status:500,headers:cors});}});
